include ../common.mak

TESTS := add/ misc/ summary/ extract/ demangle/ exception/ gcov-tool/ branch/ merge/ format errs multiple follow initializer lambda mcdc coverage/ scheduling/ names

clean: clean_echo clean_subdirs
