include ../common.mak

TESTS := parallel_parse parallel_fail fork_throttle errs scheduling extract exception xs_test mcdc add/ misc/ summary/ demangle/ gcov-tool/ branch/ merge/ format multiple follow initializer lambda coverage/ names serialization/ tempdir/

clean: clean_echo clean_subdirs
