include ../../common.mak

TESTS := help.sh version.sh profile.sh split_char.sh zerocounters.sh language.sh

clean:
	rm -f *.log *.json *.info *.c *.cpp *.CPP
	rm -rf mpl.d nobin.d fakefind zc_dir 'q$$x'"'"'dir'
