.TH lcovrc 5 "LCOV 1.16" 2022\-06\-02 "User Manuals"

.SH NAME
lcovrc \- lcov configuration file

.SH DESCRIPTION
The
.I lcovrc
file contains configuration information for the
.B lcov
code coverage tool (see
.BR lcov (1)).
.br

The system\-wide configuration file is located at
.IR /etc/lcovrc .
To change settings for a single user, place a customized copy of this file at
location
.IR ~/.lcovrc .
Where available, command\-line options override configuration file settings.

The
.I genhtml, lcov,
and
.I geninfo
commands also support the
.I \-\-config\-file
option, which can be used to specify one or more files which should be used instead of the system or user default rc files.
Multiple options files may be useful if you have both project- and team-specific common options and want to ensure consistency across multiple users.  If multiple \-\-config\-file options are applied in the order they appear.
Note that the "\-\-config\-file" option name must be specified in full and cannot be abbreviated.  An error will occur if the option is not recognized.

Lines in a configuration file can either be:
.IP "     *"
empty lines or lines consisting only of white space characters. These lines are
ignored.
.IP "     *"
comment lines which start with a hash sign ('#'). These are treated like empty
lines and will be ignored.
.IP "     *"
statements in the form
.RI ' key " = " value '.

.IP "     *"
Values may be taken from environment variables via the syntax

.RI ' key " = " ... $ENV{ENV_VAR_NAME} ...'.

.RI
The substring '$ENV{ENV_VAR_NAME}' is replaced by the value of the environmetn variable.

.RI
One or more environment variables may be used to set the RC value.
'key' is ignored if any of the environment variables are not set in your user environment.

.PP
A list of valid statements and their description can be found in
section 'OPTIONS' below.

Both 'list' and 'scalar' (non list) options are supported in the lcovrc file.

For scalar (non list) options:
.IP "     *"
if specified on the command line and in the lcovrc file, the value specified on the command line wins.
The value from the RC file is ignored.
.IP "     *"
Scalar options include:
.RI 'genhtml_criteria_script " = " ...'
,
.RI 'genhtml_annotate_script " = " ...'
,
.RI 'version_script " = " ...'
, etc.
.PP
.PP

.PP
For list options:
.IP "     *"
the RC file entry can be used multiple times; each use appends to the list.
.br
For example, the entry below will result in two 'omit' patterns which will both be checked:
.IP "      "
# note explicit start/end line markers in the regexp
.br
omit_lines = ^\s+//\s*MY_EXCLUDE_MARKER\s*$
.br
# Note that the regexp below matches anywhere on the line
.br
omit_lines = NR_CM_DBG_PRINT

.IP "     *"
If entries are specified on the command line, then the RC file entries are ignored:  command line wins.
If entries are specified in more than one RC file (i.e., multiple \-\-config\-file arguments are supplied), then RC files are applied in order of appearance, and list entries are appended in order.  For most list-type options, order is not important.


.IP "     *"
list options include:
.RI 'filter " = " ...'
,
.RI 'exclude " = " ...'
.
.RI 'include " = " ...'
,
.RI 'substitute " = " ...'
,
.RI 'omit_lines " = " ...'
, etc.

.PP
.PP

.B Example configuration:
.IP
#
.br
# Example LCOV configuration file
.br
#
.br

# External style sheet file
.br
#genhtml_css_file = gcov.css
.br

# Use 'dark' mode display (light foreground/dark background)
.br
# rather than default
.br
#genhtml_dark_mode = 1
.br

# Alternate header text to use at top of each page
.br
#genhtml_header = Coverage report for my project

.br

# Alternate footer text to use at the bottom of each page
.br
#genhtml_footer = My footer text
.br

# Coverage rate limits
.br
genhtml_hi_limit = 90
.br
genhtml_med_limit = 75
.br

# Ignore some errors (comma-separated list)
.br
#ignore_errors = empty,mismatch
.br

# If set, do not stop when an 'ignorable error' occurs - try
.br
#  to generate a result, however flawed.  This is equivalent to
.br
#  the '--keep-going' command line switch.
.br
# Default is 1:  stop when error occurs
.br
#stop_on_error = 1

# list of file extensions which should be treated as C/C++ code
.br
# (comma-separated list)
.br
#c_file_extensions = h,c,cpp,hpp
.br

# list of file extensions which should be treated as RTL code
.br
# (e.g., Verilog) (comma-separated list)
.br
#rtl_file_extensions = v,vh,sv
.br

# maxmimum number of lines to look at, when filtering bogus branch expressions
.br
#filter_lookahead = 5
.br

# if nonzero, bitwise operators '|', '&', '~' indicate conditiional expressions
.br
#filter_bitwise_conditional = 1
.br

# Width of line coverage field in source code view
.br
genhtml_line_field_width = 12
.br

# Width of branch coverage field in source code view
.br
genhtml_branch_field_width = 16
.br

# Width of overview image
.br
genhtml_overview_width = 80
.br

# Resolution of overview navigation
.br
genhtml_nav_resolution = 4
.br

# Offset for source code navigation
.br
genhtml_nav_offset = 10
.br

# Do not remove unused test descriptions if non\-zero
.br
genhtml_keep_descriptions = 0
.br

# Do not remove prefix from directory names if non\-zero
.br
genhtml_no_prefix = 0
.br

# Do not create source code view if non\-zero
.br
genhtml_no_source = 0
.br

# Specify size of tabs
.br
genhtml_num_spaces = 8
.br

# Highlight lines with converted\-only data if non\-zero
.br
genhtml_highlight = 0
.br

# Include color legend in HTML output if non\-zero
.br
genhtml_legend = 0
.br

# Include HTML file at start of HTML output
.br
#genhtml_html_prolog = prolog.html
.br

# Include HTML file at end of HTML output
.br
#genhtml_html_epilog = epilog.html
.br

# Use custom HTML file extension
.br
#genhtml_html_extension = html
.br

# Compress all generated html files with gzip.
.br
#genhtml_html_gzip = 1
.br

# Include sorted overview pages
.br
genhtml_sort = 1
.br

# Display coverage data in hierarchical directory structure
.br
# (rather than flat/3 level)
.br
#genhtml_hirearchical = 1
.br

# Include function coverage data display
.br
#genhtml_function_coverage = 1
.br

# Include branch coverage data display
.br
#genhtml_branch_coverage = 1
.br

# Specify the character set of all generated HTML pages
.br
genhtml_charset=UTF\-8
.br

# Allow HTML markup in test case description text if non\-zero
.br
genhtml_desc_html=0
.br

# Specify the precision for coverage rates
.br
#genhtml_precision=1
.br

# Show missed counts instead of hit counts
.br
#genhtml_missed=1
.br

# Demangle C++ symbols
.br
#genhtml_demangle_cpp=1
.br

# Name of the tool used for demangling C++ function names
.br
#genhtml_demangle_cpp_tool = c++filt
.br

# Specify extra parameters to be passed to the demangling tool
.br
#genhtml_demangle_cpp_params = ""
.br

# Location of the gcov tool
.br
#geninfo_gcov_tool = gcov
.br

# Adjust test names if non\-zero
.br
#geninfo_adjust_testname = 0
.br

# Calculate a checksum for each line if non\-zero
.br
geninfo_checksum = 0
.br

# Enable libtool compatibility mode if non\-zero
.br
geninfo_compat_libtool = 0
.br

# Specify whether to capture coverage data for external source
.br
# files
.br
#geninfo_external = 1
.br

# Use gcov's --all-blocks option if non-zero
.br
#geninfo_gcov_all_blocks = 1
.br

# Specify compatiblity modes (same as \-\-compat option
.br
# of geninfo)
.br
#geninfo_compat = libtool=on, hammer=auto, split_crc=auto
.br

# Adjust path to source files by removing or changing path
.br
# components that match the specified pattern (Perl regular
.br
# expression format)
.br
#geninfo_adjust_src_path = /tmp/build => /usr/src

# Specify if geninfo should try to automatically determine
.br
# the base-directory when collecting coverage data.
.br
geninfo_auto_base = 1
.br

# Use gcov intermediate format? Valid values are 0, 1, auto
.br
geninfo_intermediate = auto
.br

# Directory containing gcov kernel files
.br
lcov_gcov_dir = /proc/gcov
.br

# Location for temporary directories
.br
lcov_tmp_dir = /tmp
.br

# Show full paths during list operation if non\-zero
.br
lcov_list_full_path = 0
.br

# Specify the maximum width for list output. This value is
.br
# ignored when lcov_list_full_path is non\-zero.
.br
lcov_list_width = 80
.br

# Specify the maximum percentage of file names which may be
.br
# truncated when choosing a directory prefix in list output.
.br
# This value is ignored when lcov_list_full_path is non\-zero.
.br
lcov_list_truncate_max = 20

# Specify if function coverage data should be collected and
.br
# processed.
.br
lcov_function_coverage = 1
.br

# Specify if branch coverage data should be collected and
.br
# processed.
.br
lcov_branch_coverage = 0
.br

# Ask LCOV to return non-zero exit code if line coverage is
.br
# below specified threshold percentage.
.br
lcov_fail_under_lines = 97.5
.br

# Specify JSON module to use, or choose best available if
.br
# set to auto
.br
lcov_json_module = auto
.br

.PP

.SH OPTIONS

.BR genhtml_css_file " ="
.I filename
.IP
Specify an external style sheet file. Use this option to modify the appearance of the HTML output as generated by
.BR genhtml .
During output generation, a copy of this file will be placed in the output
directory.
.br

This option corresponds to the \-\-css\-file command line option of
.BR genhtml .
.br

By default, a standard CSS file is generated.
.PP

.BR genhtml_header " ="
.I string
.IP

Specify header text to use ta top of each HTML page.
.br

This option corresponds to the \-\-header\-title command line option of
.BR genhtml .
.br
Default is "LCOV - (differential )? coverage report"

.PP

.BR genhtml_footer " ="
.I string
.IP
Specify footer text to use at bottom of each HTML page.
.br

This option corresponds to the \-\-footer command line option of
.BR genhtml .
.br

Default is LCOV tool version string.

.PP

.BR genhtml_dark_mode " ="
.IR  0 | 1
.IP
If non-zero, display using light text on dark background rather than dark text on light background.
.br

This option corresponds to the \-\-dark\-mode command line option of
.BR genhtml .
.br

By default, a 'light' palette is used.
.PP

.BR genhtml_hi_limit "  ="
.I hi_limit
.br
.BR genhtml_med_limit " ="
.I med_limit
.br
.IP
Specify coverage rate limits for classifying file entries. Use this option to
modify the coverage rates (in percent) for line, function and branch coverage at
which a result is classified as high, medium or low coverage. This
classification affects the color of the corresponding entries on the overview
pages of the HTML output:
.br

High:   hi_limit  <= rate <= 100        default color: green
.br
Medium: med_limit <= rate < hi_limit    default color: orange
.br
Low:    0         <= rate < med_limit   default color: red
.br

Defaults are 90 and 75 percent.
.PP


.BR rtl_file_extensions " ="
.IR str[,str]+
.IP
Specify a comma-separage list of file extensions which should be assumed to be RTL code (e.g., Verilog).
.br

If not specified, the default set is 'v,vh,sv,vhdl?'.
There is no command line option equivalent.
.br
This option is used by genhtml and lcov.

.PP

.BR c_file_extensions " ="
.IR str[,str]+
.IP
Specify a comma-separage list of file extensions which should be assumed to be C/C++ code.
.br

If not specified, the default set is 'c,h,i,C,H,I,icc,cpp,cc,cxx,hh,hpp,hxx'.
There is no command line option equivalent.
.br
This option is used by genhtml and lcov.

.PP

.BR filter_lookahead " ="
.IR integer
.IP
Specify the maximum number of lines to look at when filtering bogus branch expressions.
A larger number may catch more cases, but will increase execution time.
.br

If not specified, the default set is 10.
There is no command line option equivalent.
.br
This option is used by genhtml and lcov.

.PP

.BR filter_bitwise_conditional " ="
.IR 0|1
.IP
If set to non-zero value, bogus branch filtering will assume that expressions containing  bitwise operators '&', '|', '~' are conditional expressions - and will not filter them out.
.br

If not specified, the default set is 0 (do not treat them as conditional).
There is no command line option equivalent.
.br
This option is used by genhtml and lcov.

.PP

.BR ignore_errors " ="
.IR message_type(,message_type)*
.IP
Specify a  message type which should be ignored.
.br

This option can be used multiple times in the lcovrc file to ignore multiple message types.

This option is equivalent to the \-\-ignore\-errors option to geninfo, genhtml, or lcov.  Note that the lcovrc file message list is not applied (those messages NOT ignored) if the '\-\-ignore\-errors' command line option is specified.
.br
This option is used by genhtml, lcov, and geninfo.

.PP

.BR stop_on_error " = "
.IR 0|1
.IP
If set to 1, tell the tools to ignore errors and keep going to try to generate a result - however flawed or incomplete that result might be.
Note that ignoring some errors may lead to other errors.

.br

This is equivalent to the 
.I '\-\-keep\-going'
command line option.

Default is 1:  stop when error occurs.

If the 
.I 'ignore_error msgType'
option is also used, then those messages will be treated as warnings rather than errors (or will be entirely suppressed if the message type appears multiple times in the ignore_messages option).

This option is used by genhtml, lcov, and geninfo.

.PP

.BR genhtml_line_field_width " ="
.I number_of_characters
.IP
Specify the width (in characters) of the source code view column containing
line coverage information.
.br

Default is 12.
.PP

.BR genhtml_branch_field_width " ="
.I number_of_characters
.IP
Specify the width (in characters) of the source code view column containing
branch coverage information.
.br

Default is 16.
.PP

.BR genhtml_overview_width " ="
.I pixel_size
.IP
Specify the width (in pixel) of the overview image created when generating HTML
output using the \-\-frames option of
.BR genhtml .
.br

Default is 80.
.PP

.BR genhtml_nav_resolution " ="
.I lines
.IP
Specify the resolution of overview navigation when generating HTML output using
the \-\-frames option of
.BR genhtml .
This number specifies the maximum difference in lines between the position a
user selected from the overview and the position the source code window is
scrolled to.
.br

Default is 4.
.PP


.BR genhtml_nav_offset " ="
.I lines
.IP
Specify the overview navigation line offset as applied when generating HTML
output using the \-\-frames option of
.BR genhtml.
.br

Clicking a line in the overview image should show the source code view at
a position a bit further up, so that the requested line is not the first
line in the window.  This number specifies that offset.
.br

Default is 10.
.PP


.BR genhtml_keep_descriptions " ="
.IR 0 | 1
.IP
If non\-zero, keep unused test descriptions when generating HTML output using
.BR genhtml .
.br

This option corresponds to the \-\-keep\-descriptions option of
.BR genhtml .
.br

Default is 0.
.PP

.BR genhtml_no_prefix " ="
.IR 0 | 1
.IP
If non\-zero, do not try to find and remove a common prefix from directory names.
.br

This option corresponds to the \-\-no\-prefix option of
.BR genhtml .
.br

Default is 0.
.PP

.BR genhtml_no_source " ="
.IR 0 | 1
.IP
If non\-zero, do not create a source code view when generating HTML output using
.BR genhtml .
.br

This option corresponds to the \-\-no\-source option of
.BR genhtml .
.br

Default is 0.
.PP

.BR genhtml_num_spaces " ="
.I num
.IP
Specify the number of spaces to use as replacement for tab characters in the
HTML source code view as generated by
.BR genhtml .
.br

This option corresponds to the \-\-num\-spaces option of
.BR genthml .
.br

Default is 8.

.PP

.BR genhtml_highlight " ="
.IR 0 | 1
.IP
If non\-zero, highlight lines with converted\-only data in
HTML output as generated by
.BR genhtml .
.br

This option corresponds to the \-\-highlight option of
.BR genhtml .
.br

Default is 0.
.PP

.BR genhtml_legend " ="
.IR 0 | 1
.IP
If non\-zero, include a legend explaining the meaning of color coding in the HTML
output as generated by
.BR genhtml .
.br

This option corresponds to the \-\-legend option of
.BR genhtml .
.br

Default is 0.
.PP

.BR genhtml_html_prolog " ="
.I filename
.IP
If set, include the contents of the specified file at the beginning of HTML
output.

This option corresponds to the \-\-html\-prolog option of
.BR genhtml .
.br

Default is to use no extra prolog.
.PP

.BR genhtml_html_epilog " ="
.I filename
.IP
If set, include the contents of the specified file at the end of HTML output.

This option corresponds to the \-\-html\-epilog option of
.BR genhtml .
.br

Default is to use no extra epilog.
.PP

.BR genhtml_html_extension " ="
.I extension
.IP
If set, use the specified string as filename extension for generated HTML files.

This option corresponds to the \-\-html\-extension option of
.BR genhtml .
.br

Default extension is "html".
.PP

.BR genhtml_html_gzip " ="
.IR 0 | 1
.IP
If set, compress all html files using gzip.

This option corresponds to the \-\-html\-gzip option of
.BR genhtml .
.br

Default extension is 0.
.PP

.BR genhtml_sort " ="
.IR 0 | 1
.IP
If non\-zero, create overview pages sorted by coverage rates when generating
HTML output using
.BR genhtml .
.br

This option can be set to 0 by using the \-\-no\-sort option of
.BR genhtml .
.br

Default is 1.
.PP

.BR genhtml_hierarchical " ="
.IR 0 | 1
.IP
If non\-zero, the HTML report will follow the hierarchical directory structure of the source code.
.br

This option is equivalent to using the \-\-hierarchical command line option of
.BR genhtml .
.br

Default is 0.
.PP

.BR genhtml_show_navigation " ="
.IR 0 | 1
.IP
If non\-zero, the 'source code' view summary table will contain hyperlinks from the number to the first source line in the corresponding category ('Hit' or 'Not hit') in the non-differential coverage report.
Source code hyperlinks are always enabled in differential coverage reports.
.br

This option is equivalent to using the \-\-show\-navigation command line option of
.BR genhtml .
.br

Default is 0.
.PP

.BR genhtml_function_coverage " ="
.IR 0 | 1
.IP
If non\-zero, include function coverage data when generating HTML output using
.BR genhtml .
.br

This option can be set to 0 by using the \-\-no\-function\-coverage option of
.BR genhtml .
.br

Default is 1.
.PP

.BR genhtml_branch_coverage " ="
.IR 0 | 1
.IP
If non\-zero, include branch coverage data when generating HTML output using
.BR genhtml .
.br

This option can be set to 0 by using the \-\-no\-branch\-coverage option of
.BR genhtml .
.br

Default is 1.
.PP

.BR genhtml_charset " ="
.I charset
.IP
Specify the character set of all generated HTML pages.
.br

Use this option if the source code contains characters which are not
part of the default character set. Note that this option is ignored
when a custom HTML prolog is specified (see also
.BR genhtml_html_prolog ).
.br

Default is UTF-8.
.PP

.BR genhtml_demangle_cpp " ="
.IR 0 | 1
.IP
If non-zero, demangle C++ function names in function overviews.

Set this option to one if you want to convert C++ internal function
names to human readable format for display on the HTML function overview
page.  This option requires that the c++filt tool is installed (see
.BR c++filt(1)
).
.br

This option corresponds to the \-\-demangle\-cpp command line option of
.BR genhtml .
.br

Default is 0.
.PP

.BR genhtml_demangle_cpp_tool " ="
.I path_to_c++filt
.IP
Specify the location of the demangle tool (see
.BR c++filt (1))
used to convert C++ internal function names to human readable format
for display on the HTML function overview page.
.br

Default is 'c++filt'.
.PP

.BR genhtml_demangle_cpp_params " ="
.I parameters
.IP
Specify extra parameters to be passed to the demangling tool

Use this option if your environment requires additional parameters such
as --no-strip-underscore for correctly demangling C++ internal function
names. See also
.BR c++filt (1)).
.br

Default is "".
.PP

.BR genhtml_desc_html " ="
.IR 0 | 1
.IP
If non-zero, test case descriptions may contain HTML markup.

Set this option to one if you want to embed HTML markup (for example to
include links) in test case descriptions. When set to zero, HTML markup
characters will be escaped to show up as plain text on the test case
description page.
.br

Default is 0.
.PP

.BR genhtml_precision " ="
.IR  1 | 2 | 3 | 4
.IP
Specify how many digits after the decimal-point should be used for
displaying coverage rates.
.br

Default is 1.
.PP
.BR genhtml_missed " ="
.IR  0 | 1
.IP
If non-zero, the count of missed lines, functions, or branches is shown
as negative numbers in overview pages.
.br

Default is 0.
.PP

.
.BR geninfo_gcov_tool " ="
.I path_to_gcov
.IP
Specify the location of the gcov tool (see
.BR gcov (1))
which is used to generate coverage information from data files.
.br

Default is 'gcov'.
.PP

.BR geninfo_adjust_testname " ="
.IR 0 | 1
.IP
If non\-zero,  adjust test names to include operating system information
when capturing coverage data.
.br

Default is 0.
.PP

.BR geninfo_checksum " ="
.IR 0 | 1
.IP
If non\-zero, generate source code checksums when capturing coverage data.
Checksums are useful to prevent merging coverage data from incompatible
source code versions but checksum generation increases the size of coverage
files and the time used to generate those files.
.br

This option corresponds to the \-\-checksum and \-\-no\-checksum command line
option of
.BR geninfo .
.br

Default is 0.
.PP

.BR geninfo_compat_libtool " ="
.IR 0 | 1
.IP
If non\-zero, enable libtool compatibility mode. When libtool compatibility
mode is enabled, lcov will assume that the source code relating to a .da file
located in a directory named ".libs" can be found in its parent directory.
.br

This option corresponds to the \-\-compat\-libtool and \-\-no\-compat\-libtool
command line option of
.BR geninfo .
.br

Default is 1.
.PP

.BR geninfo_external " ="
.IR 0 | 1
.IP
If non\-zero, capture coverage data for external source files.

External source files are files which are not located in one of the directories
(including sub-directories)
specified by the \-\-directory or \-\-base\-directory options of
.BR lcov / geninfo .

Default is 1.
.PP

.BR geninfo_gcov_all_blocks " ="
.IR 0 | 1
.IP
If non\-zero, call the gcov tool with option --all-blocks.

Using --all-blocks will produce more detailed branch coverage information for
each line. Set this option to zero if you do not need detailed branch coverage
information to speed up the process of capturing code coverage or to work
around a bug in some versions of gcov which will cause it to endlessly loop
when analysing some files.

Default is 1.
.PP

.BR geninfo_compat " ="
.IR mode = value [, mode = value ,...]
.IP
Specify that geninfo should enable one or more compatibility modes
when capturing coverage data.

This option corresponds to the \-\-compat command line option of
.BR geninfo .

Default is 'libtool=on, hammer=auto, split_crc=auto'.
.PP

.BR geninfo_adjust_src_path " ="
.IR pattern " => " replacement
.br
.BR geninfo_adjust_src_path " ="
.I pattern
.IP
Adjust source paths when capturing coverage data.

Use this option in situations where geninfo cannot find the correct
path to source code files of a project. By providing a
.I pattern
in Perl regular expression format (see
.BR perlre (1))
and an optional replacement string, you can instruct geninfo to
remove or change parts of the incorrect source path.

.B Example:
.br

1. When geninfo reports that it cannot find source file
.br

    /path/to/src/.libs/file.c
.br

while the file is actually located in
.br

    /path/to/src/file.c
.br

use the following parameter:
.br

    geninfo_adjust_src_path = /.libs

This will remove all "/.libs" strings from the path.

2. When geninfo reports that it cannot find source file
.br

    /tmp/build/file.c
.br

while the file is actually located in
.br

    /usr/src/file.c
.br

use the following parameter:
.br

    geninfo_adjust_src_path = /tmp/build => /usr/src
.br

This will change all "/tmp/build" strings in the path to "/usr/src".
.PP

.BR geninfo_auto_base " ="
.IR 0 | 1
.IP
If non\-zero, apply a heuristic to determine the base directory when
collecting coverage data.
.br

Use this option when using geninfo on projects built with libtool or
similar build environments that work with multiple base directories,
i.e. environments, where the current working directory when invoking the
compiler ist not the same directory in which the source code file is
located, and in addition, is different between files of the same project.
.br

Default is 1.
.PP

.BR geninfo_intermediate " ="
.IR 0 | 1 | auto
.IP
Specify whether to use gcov intermediate format
.br

Use this option to control whether geninfo should use the gcov intermediate
format while collecting coverage data. The use of the gcov intermediate format
should increase processing speed. It also provides branch coverage data when
using the \-\-initial command line option.
.br

Valid values are 0 for off, 1 for on, and "auto" to let geninfo automatically
use immediate format when supported by gcov.
.br

Default is "auto".
.PP

.BR geninfo_no_exception_branch " ="
.IR 0 | 1
.IP
Specify whether to exclude exception branches from branch coverage.
.br

Default is 0.
.PP

.BR lcov_gcov_dir " ="
.I path_to_kernel_coverage_data
.IP
Specify the path to the directory where kernel coverage data can be found
or leave undefined for auto-detection.
.br

Default is auto-detection.
.PP

.BR lcov_tmp_dir " ="
.I temp
.IP
Specify the location of a directory used for temporary files.
.br

Default is '/tmp'.
.PP

.BR lcov_list_full_path " ="
.IR 0 | 1
.IP
If non-zero, print the full path to source code files during a list operation.
.br

This option corresponds to the \-\-list\-full\-path option of
.BR lcov .
.br

Default is 0.
.PP

.BR lcov_list_max_width " ="
.IR width
.IP
Specify the maximum width for list output. This value is ignored when
lcov_list_full_path is non\-zero.
.br

Default is 80.
.PP

.BR lcov_list_truncate_max
.B " ="
.IR percentage
.IP
Specify the maximum percentage of file names which may be truncated when
choosing a directory prefix in list output. This value is ignored when
lcov_list_full_path is non\-zero.
.br

Default is 20.
.PP

.BR lcov_function_coverage " ="
.IR 0 | 1
.IP
Specify whether lcov should handle function coverage data.
.br

Setting this option to 0 can reduce memory and CPU time consumption
when lcov is collecting and processing coverage data, as well as
reduce the size of the resulting data files. Note that setting
.B genhtml_function_coverage
will override this option for HTML generation.
.br

Default is 1.
.PP

.BR lcov_branch_coverage " ="
.IR 0 | 1
.IP
Specify whether lcov should handle branch coverage data.
.br

Setting this option to 0 can reduce memory and CPU time consumption
when lcov is collecting and processing coverage data, as well as
reduce the size of the resulting data files. Note that setting
.B genhtml_branch_coverage
will override this option for HTML generation.
.br

Default is 0.
.PP

.BR lcov_excl_line " ="
.I expression
.IP
Specify the regular expression of lines to exclude.
.br

Default is 'LCOV_EXCL_LINE'.
.PP

.BR lcov_excl_br_line " ="
.I expression
.IP
Specify the regular expression of lines to exclude from branch coverage.
.br

Default is 'LCOV_EXCL_BR_LINE'.
.PP

.BR lcov_excl_exception_br_line " ="
.I expression
.IP
Specify the regular expression of lines to exclude from exception branch coverage.
.br

Default is 'LCOV_EXCL_EXCEPTION_BR_LINE'.
.PP

.BR lcov_fail_under_lines " ="
.I percentage
.IP
Specify line coverage threshold to lcov.  If the line coverage is below this threshold, lcov will generate all the normal result files and messages, but will return a non-zero exit code.
.br

This option is equivalent to the \-\-fail\-under\-lines lcov command line argument.

.br
The default is 0 (no threshold).

.PP

.BR profile " ="
.IR filename
.IP
If set, tells genhtml, lcov, or geninfo to generate some execution
time/profile data which can be used to motivate future optimizations.
The default is unset no data generated.

.br
This option is used by genhtml, lcov, and geninfo.

.PP

.BR parallel " ="
.IR integer
.IP
Tells genhtml, lcov, or geninfo the maximum number of simultaneous processes
to use.  Zero means to use as many cores as are available on the machine.
The default is 1 (one) - which means to process sequentially (no parallelism).

.br
This option is used by genhtml, lcov, and geninfo.

.PP

.BR genhtml_date_bins " ="
.IR integer[,integer..]
.IP
This option is equivalent to the "genhtml \-\-date\-bins" option.
See the genhtml man page for details.

This option can be used multiple tiems in the lcovrc file to set multiple cutpoints.
The cutpoints specified in the lcovrc file are appended to the cutpoints (if any) specified on the command line.

.PP

.BR genhtml_annotate_script " ="
.IR path_to_executable
.IP
This option is equivalent to the "genhtml \-\-annotate\-script" option.
See the genhtml man page for details.

.PP

.BR genhtml_criteria_script " ="
.IR path_to_executable
.IP
This option is equivalent to the "genhtml \-\-criteria\-script" option.
See the genhtml man page for details.

.PP

.BR version_script " ="
.IR path_to_executable
.IP
This option is equivalent to the geninfo/lcov/genhtml "\-\-version\-script" option.
See the genhtml man page for details.

.PP

.BR filter " ="
.IR str[,str...]
.IP

This option is equivalent to the \-\-filter option to geninfo, lcov, and genhtml.
See the genhtml man page for details.

This option can be used multiple tiems in the lcovrc file to enable multiple filters.
The filters specified in the lcovrc file are appended to the list specified on the command line.

.br
This option is used by genhtml, lcov, and geninfo.

.PP

.BR exclude " ="
.IR glob_pattern
.IP

This option is equivalent to the \-\-exclude option to geninfo, lcov, and genhtml.
See the lcov man page for details.;

This option can be used multiple tiems in the lcovrc file to specify multiple patterns to exclude.
The patterns specified in the lcovrc file are appended to the list specified on the command line.

.br
This option is used by genhtml, lcov, and geninfo.

.PP

.BR include " ="
.IR glob_pattern
.IP

This option is equivalent to the \-\-include option to geninfo, lcov, and genhtml.
See the lcov man page for details.;

This option can be used multiple tiems in the lcovrc file to specify multiple patterns to include.
The patterns specified in the lcovrc file are appended to the list specified on the command line.

.br
This option is used by genhtml, lcov, and geninfo.

.PP

.BR substitute " ="
.IR regexp
.IP

This option is equivalent to the \-\-substitute option to geninfo, lcov, and genhtml.
See the lcov man page for details.;

This option can be used multiple tiems in the lcovrc file to specify multiple subsitution patterns.
The patterns specified in the lcovrc file are appended to the list specified on the command line.

.br
This option is used by genhtml, lcov, and geninfo.

.PP

.BR omit_lines " ="
.IR regexp
.IP

This option is equivalent to the \-\-omit\-lines option to geninfo, lcov, and genhtml.
See the genhtml man page for details.;

This option can be used multiple tiems in the lcovrc file to specify multiple patterns to exclude.
The patterns specified in the lcovrc file are appended to the list specified on the command line.

.br
This option is used by genhtml, lcov, and geninfo.

.BR lcov_json_module " ="
.IR module | auto
.IP
Specify the JSON module to use, or choose best available from a set of
alternatives if set to 'auto'. Note that some JSON modules are slower than
others (notably JSON::PP can be very slow compared to JSON::XS).
.br

Default is 'auto'.

.PP


.SH FILES

.TP
.I /etc/lcovrc
The system\-wide
.B lcov
configuration file.

.TP
.I ~/.lcovrc
The individual per\-user configuration file.
.PP

.SH SEE ALSO
.BR lcov (1),
.BR genhtml (1),
.BR geninfo (1),
.BR gcov (1)
