# ============================================================================
# setup_common.sh -- shared setup for the split 'extract' lcov tests.
#
# The original monolithic extract.sh was split into extract1.sh and extract2.sh
# so its ~55 capture invocations (the dominant cost) can run as two independent
# tests in parallel.  Each part runs in its own working directory (partN.d) so
# the parts cannot collide on the fixed output filenames (external.info,
# internal.info, separate/, errs/, mytest/, ...) or on the shared build
# artifacts (extract.gcno/.gcda).
#
# This file is *sourced* by each part after it has sourced ../../common.tst.
# It performs only the work that is safe to share:
#   - derive the compiler-version-dependent option variables,
#   - create and cd into the part's private working directory,
#   - symlink in the source and support files the tests reference by relative
#     path,
#   - compile extract.cpp (produces the .gcno; does NOT run a.out).
#
# It deliberately does NOT run './a.out' or perform any capture: extract1.sh's
# '--initial' capture tests must run *before* any runtime coverage data
# (.gcda) exists, so running a.out here would change their behaviour.  Each part
# runs a.out and produces the captures it needs itself.
#
# extract.sh uses no --version-script, so (unlike genhtml/simple) there is no p4
# version-identity requirement: plain symlinks back to the real source/support
# files are sufficient.
#
# Callers set WORKDIR (e.g. WORKDIR=part1.d) before sourcing.
# ============================================================================

if [ -z "$WORKDIR" ] ; then
    echo "setup_common.sh: WORKDIR not set" >&2
    exit 1
fi

# SRCDIR = the real test directory (where the source and support files live);
# we are sitting in it because common.tst did ROOT=`pwd`.
SRCDIR=`pwd`

setup_die() {
    echo "setup_common: $1" >&2
    exit 1
}

#use geninfo for capture - so we can collect coverage info
CAPTURE=$GENINFO_TOOL
#CAPTURE="$LCOV_TOOL --capture --directory"
UNREACHABLE="--unreachable-script $SCRIPT_DIR/unreach.pm"

LCOV_OPTS="--branch-coverage $PARALLEL $PROFILE"
# gcc/4.8.5 (and possibly other old versions) generate inconsistent line/function data
IFS='.' read -r -a VER <<< `${CC} -dumpversion`
if [ "${VER[0]}" -lt 5 ] ; then
    IGNORE="--ignore inconsistent"
    # and filter exception branches to avoid spurious differences for old compiler
    FILTER='--filter branch'
fi

if ! type ${CXX} >/dev/null 2>&1 ; then
        echo "Missing tool: ${CXX}" >&2
        exit 2
fi

COMPILE_OPTS="--coverage"
# gcc 5 and 6 just do not work for initial capture
if [[ "${VER[0]}" -gt 4 && "${VER[0]}" -lt 7 ]] ; then
    # no data generated by initial capture
    IGNORE_EMPTY="--ignore empty"
    NO_INITIAL_CAPTURE=1
elif [ "${VER[0]}" -ge 14 ] ; then
    ENABLE_MCDC=1
    # enable MCDC
    LCOV_OPTS="$LCOV_OPTS --mcdc"
    COMPILE_OPTS="$COMPILE_OPTS -fcondition-coverage"
fi

if [ "${VER[0]}" -lt 8 ] ; then
    # cannot generate branch data unless 'intermediate'
    IGNORE_USAGE="--ignore usage"
    DERIVE_END='--rc derive_function_end_line=0'
fi

if [ "${VER[0]}" -lt 5 ] ; then
    EMPTY_BRANCH="--ignore empty"
fi

# --------------------------------------------------------------------------
# Create and enter the private working directory.  A previous run's 'separate'
# subtree may contain deliberately-unwritable directories (chmod ugo-w), so
# make the whole tree writable before removing it.
# --------------------------------------------------------------------------
if [ -d "$SRCDIR/$WORKDIR" ] ; then
    chmod -R u+rwx "$SRCDIR/$WORKDIR" 2>/dev/null
    rm -rf "$SRCDIR/$WORKDIR"
fi
mkdir -p "$SRCDIR/$WORKDIR"
cd "$SRCDIR/$WORKDIR" || exit 1

# Bring in the source and support files the tests reference by relative path.
# Symlinks are fine: there is no version-script/p4-identity requirement here.
ln -s "$SRCDIR/extract.cpp"       extract.cpp
ln -s "$SRCDIR/unused.c"          unused.c
ln -s "$SRCDIR/history.sh"        history.sh
ln -s "$SRCDIR/testContext.sh"    testContext.sh
ln -s "$SRCDIR/fakeResolve.sh"    fakeResolve.sh
ln -s "$SRCDIR/brokenCallback.pm" brokenCallback.pm
ln -s "$SRCDIR/envVar.rc"         envVar.rc
ln -s "$SRCDIR/envErr.rc"         envErr.rc
ln -s "$SRCDIR/list.gold"         list.gold
ln -s "$SRCDIR/list_mcdc.gold"    list_mcdc.gold

# compile (produces extract.gcno; a.out is run later, by each part as needed)
${CXX} -std=c++1y $COMPILE_OPTS extract.cpp
if [ 0 != $? ] ; then
    echo "Error:  unexpected error from g++"
    exit 1
fi
