#!/bin/bash

set +x

source ../../common.tst

rm -f *.info* *.gc* a.out *.log
rm -rf nav no_nav annotate diff

if [[ 1 == $CLEAN_ONLY ]] ; then
    exit 0
fi

if ! type ${CXX} >/dev/null 2>&1 ; then
        echo "Missing tool: ${CXX}" >&2
        exit 2
fi

# gcc/4.8.5 (and possibly other old versions) generate inconsistent line/function data
IFS='.' read -r -a VER <<< `${CC} -dumpversion`
if [ "${VER[0]}" -lt 5 ] ; then
    IGNORE="--ignore inconsistent"
    # and filter exception branches to avoid spurious differences for old compiler
    FILTER='--filter branch'
fi

if [ "" != "$COVER" ] ; then
    CAPTURE=$GENINFO_TOOL
else
    CAPTURE="$LCOV_TOOL --capture --directory"
fi

LCOV_OPTS="--branch-coverage $PARALLEL $PROFILE"

COMPILE_OPTS="--coverage"
# gcc 5 and 6 just do not work for initial capture
if [[ "${VER[0]}" -gt 4 && "${VER[0]}" -lt 7 ]] ; then
    # no data generated by initial capture
    IGNORE_EMPTY="--ignore empty"
    NO_INITIAL_CAPTURE=1
elif [ "${VER[0]}" -ge 14 ] ; then
    ENABLE_MCDC=1
    # enable MCDC
    LCOV_OPTS="$LCOV_OPTS --mcdc"
    COMPILE_OPTS="$COMPILE_OPTS -fcondition-coverage"
fi

if [ "${VER[0]}" -lt 8 ] ; then
    # cannot generate branch data unless 'intermediate'
    IGNORE_USAGE="--ignore usage"
    DERIVE_END='--rc derive_function_end_line=0'
fi

if [ "${VER[0]}" -lt 5 ] ; then
    EMPTY_BRANCH="--ignore empty"
fi

${CXX} -std=c++1y $COMPILE_OPTS counts.cpp
if [ 0 != $? ] ; then
    echo "Error:  unexpected error from ${CXX}"
    exit 1
fi

./a.out
if [ 0 != $? ] ; then
    echo "Error:  unexpected error from a.out"
    exit 1
fi

status=0
$COVER $CAPTURE . $LCOV_OPTS -o count.info --include counts.cpp $IGNORE $FILTER
if [ 0 != $? ] ; then
    echo 'lcov --capture failed'
    status=1
    if [ $KEEP_GOING == 0 ] ; then
        exit 1
    fi
fi

$COVER $GENHTML_TOOL count.info -o no_nav $LCOV_OPTS 2>&1 | tee no_nav.log
if [ 0 != ${PIPESTATUS[0]} ] ; then
    echo 'genhtml no_nav failed'
    status=1
    if [ $KEEP_GOING == 0 ] ; then
        exit 1
    fi
fi

$COVER $GENHTML_TOOL  count.info -o nav $LCOV_OPTS --show-navigation 2>&1 | tee nav.log
if [ 0 != ${PIPESTATUS[0]} ] ; then
    echo 'genhtml nav failed'
    status=1
    if [ $KEEP_GOING == 0 ] ; then
        exit 1
    fi
fi

$COVER $GENHTML_TOOL count.info -o annotate --annotate-script $ANNOTATE $LCOV_OPTS --show-navigation --ignore annotate,inconsistent 2>&1 | tee annotate.log
if [ 0 != ${PIPESTATUS[0]} ] ; then
    echo 'genhtml annotate failed'
    status=1
    if [ $KEEP_GOING == 0 ] ; then
        exit 1
    fi
fi

$COVER $GENHTML_TOOL count.info --baseline-file count.info -o diff $LCOV_OPTS --show-navigation --ignore inconsistent 2>&1 | tee diff.log
if [ 0 != ${PIPESTATUS[0]} ] ; then
    echo 'genhtml annotate failed'
    status=1
    if [ $KEEP_GOING == 0 ] ; then
        exit 1
    fi
fi

COUNTS=()
COUNTS[0]='branches.+13 of 26 branches'
PATS=()
PATS[0]='branch: UNC:13 GNC:13'

if [ "$ENABLE_MCDC" == 1 ] ; then
    COUNTS[1]='MC/DCs.+11 of 16 MC/DCs'
    PATS[1]='mcdc: UNC:5 GNC:11'
fi

if [ "${VER[0]}" -lt 5 ] ; then
    COUNTS[0]='branches.+11 of 16 branches'
    PATS[0]='branch: UNC:5 GNC:11'
fi

for log in no_nav.log nav.log annotate.log diff.log ; do
    for pat in "${COUNTS[@]}" ; do

	grep -E "$pat" $log

	if [ 0 != $? ] ; then
	    echo "did not find '$pat' in $log"
	    status=1
	    if [ $KEEP_GOING == 0 ] ; then
		exit 1
	    fi
	fi
    done
done

for pat in "${PATS[@]}" ; do

    grep -E "$pat" nav.log

    if [ 0 != $? ] ; then
	echo "did not find '$pat' in nav.log"
	status=1
	if [ $KEEP_GOING == 0 ] ; then
	    exit 1
	fi
    fi
done

if [ "x$COVER" != "x" ] ; then
    generate_coverage names $LOCAL_COVERAGE
fi

if [ 0 != $status ] ; then
    echo "Tests failed"
else
    echo "Tests passed"
fi
exit $status
