#!/bin/bash
set +x

# ============================================================================
# jacoco2lcov is a wrapper:  it runs 'java -jar jacococli.jar report', then
#   xml2lcov, reads the xml2lcov result, then applies common LCOV options and
#   writes the result out.
#
# 'java' is a stub, written below.  It records the command line it was given
#   and writes a fixture report to the file named by '--xml', which lets this
#   test run on a machine with neither a JDK nor a JaCoCo installation, and
#   lets it check exactly what jacoco2lcov asked JaCoCo to do.
#
# Cases:
#   1. --help and the usage errors:  no .exec file, an unreadable one, no class
#      location, no source directory, one of its own options written in a way
#      Getopt::Long cannot use
#   2. jacococli.jar discovery:  --jar, JACOCOCLI_JAR, JACOCO_HOME (both
#      layouts), and the errors when each of those names nothing readable
#   3. the java command line:  the .exec files, one --classfiles per class
#      location, one --sourcefiles per source directory, and --xml
#   4. branch and function coverage are always generated by xml2lcov, so
#      jacoco2lcov defaults both of them on rather than let the read back in
#      drop them.
#   5. the common options are applied to the translated data:  the exclusions,
#      the filters and the comments reach the result, and an option
#      jacoco2lcov does not know is an error rather than something to forward
#   6. every argument which is not an option is an .exec file, whatever it
#      is called and wherever on the line it is - including after '--', which
#      ends the options
#   7. a run which asks nothing of the data produces what xml2lcov produced;
#      --xml keeps the intermediate report, and without it, it is temporary
#   8. -p expands an Eclipse/Maven plugin root, or a directory of them, into
#      the -s and -c options it implies - and with none of -s, -c and -p named,
#      the current directory is searched the same way
#   9. a failing subcommand is reported, whether it exited non-zero,
#      died on a signal, or could not be executed
#  10. the 'inconsistent' hint - the error a JaCoCo-derived report is
#      most likely to produce when it is read back in:
#        a covered line whose branches were all missed, and
#        a method which was never entered whose derived extent holds a
#         covered line
#  11. which java gets run:  --java, then $JAVA_HOME/bin/java, then the PATH
#  12. --verbose names each command before it runs, and --keep-going
#      reaches the step which understands it
#  13. -d names the directory to work in:  relative paths on the command line
#      are taken relative to it, an absolute path below it is recorded relative
#      to it and one outside it is not, and an execution data argument which
#      names a directory stands for the '.exec' files below it
#  14. the path the tool was invoked by decides where it looks for the tools it
#      runs:  a run through a link somewhere else still uses
#      the xml2lcov installed beside the script, and a run through a link whose
#      name is a Windows path - which is what a git-bash perl is handed - keeps
#      that name out of both the messages and the temporary directory
#  15. the tools are found on Windows too, where '-x' answers from the file name
#      extension:  a '.bat' beside the script is preferred and the extensionless
#      script is used anyway, while a name which is nothing at all is still an
#      error
#  16. a Windows path is translated to the name a git-bash, MSYS or Cygwin perl
#      can open - the mount point of the drive, and forward slashes - in every
#      path option, in the execution data arguments and in the name the script
#      was invoked by.  Either separator arrives, and so does a mixture of them,
#      a relative path and a UNC name;  a drive which is not mounted is left as
#      it stands
#  17. '--version-script' computes a version for the translated data, without
#      needing 'compute_file_version' to be asked for as well - and an explicit
#      'compute_file_version=0' still turns it off
# ============================================================================

if [[ "x" == ${LCOV_HOME}x ]] ; then
    if [ -f ../../bin/lcov ] ; then
        LCOV_HOME=../..
    fi
fi
source ../common.tst

# common.tst names the tools only when the environment has not already done it,
#  and the environment a 'make check' provides does not include this one - so
#  say where it is, the way the other testcases whose tool common.mak does not
#  export do
if [ 'x' == "x$JACOCO2LCOV_TOOL" ] ; then
    JACOCO2LCOV_TOOL=${LCOV_HOME}/bin/jacoco2lcov
fi

# the fixtures below include files and directories which deliberately cannot be
#  read.  Give the permissions back once the test is done with them - and here,
#  in case an earlier run did not get that far - so that nothing else (a
#  'find', a 'grep -r', 'p4 reconcile', the next 'rm -rf') trips over them
restore_permissions()
{
    chmod -R 755 noreadplugins nonexecjavahome noreadhome 2> /dev/null
    chmod 644 noread.jar noread.exec 2> /dev/null
}

restore_permissions
chmod -R 755 noreadplugins nonexecjavahome noreadhome 2> /dev/null
chmod 644 noread.jar noread.exec 2> /dev/null
rm -rf *.info *.log *.xml *.jar *.exec plaindata src bin extra plugins emptyplugins \
    noclassplugin noreadplugins fakejava emptyhome jarhome libhome javahome \
    noreadhome pathbin nojavahome nonexecjavahome droot linkdir wintools \
    winnobat winmount 'Z:\bin\jacoco2lcov'

clean_cover

if [[ 1 == $CLEAN_ONLY ]] ; then
    exit 0
fi

STATUS=0

fail()
{
    # $1 = case label, $2.. = what went wrong
    local label=$1
    shift
    echo "ERROR ($label): $*"
    STATUS=1
    if [ $KEEP_GOING == 0 ] ; then
        exit 1
    fi
}

# write_source <path> <lines> -- a source file stand-in of the given length.
#  Nothing in this test compiles Java:  the sources exist because xml2lcov
#  drops a source file it cannot find, so the names in the fixture report have
#  to resolve to something
write_source()
{
    mkdir -p `dirname $1`
    local i=1
    while [ $i -le $2 ] ; do
        echo "// line $i"
        i=`expr $i + 1`
    done > $1
}

# ---------------------------------------------------------------------------
# the fixtures
# ---------------------------------------------------------------------------

write_source src/com/example/Widget.java 10
write_source src/com/example/Helper.java 10
mkdir -p bin extra
printf 'not really a class file\n' > bin/Widget.class
printf 'not really a jar of class files\n' > extra/classes.jar
printf 'not really execution data\n' > test.exec
#  the same, under a name which says nothing about what it is:  every argument
#   which is not an option is an execution data file, whatever it is called
printf 'not really execution data\n' > plaindata

# jacococli.jar in each of the two places JACOCO_HOME can hold it, and a
#  JACOCO_HOME with no jar in it at all
mkdir -p emptyhome libhome/lib jarhome
printf 'not really a jar\n' > libhome/lib/jacococli.jar
printf 'not really a jar\n' > jarhome/jacococli.jar
JAR=`pwd`/libhome/lib/jacococli.jar

# the report the stub 'java' writes:  Widget.java has a line with one of its
#  two branches taken, so that branch data is visible in the result, and
#  Helper.java is there to be excluded
cat > nominal.xml << 'EOF'
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE report PUBLIC "-//JACOCO//DTD Report 1.1//EN" "report.dtd">
<report name="nominal">
  <sessioninfo id="somehost-12345678" start="1700000000000" dump="1700000001000"/>
  <package name="com/example">
    <class name="com/example/Widget" sourcefilename="Widget.java">
      <method name="run" desc="()V" line="5">
        <counter type="BRANCH" missed="1" covered="1"/>
        <counter type="LINE" missed="0" covered="2"/>
        <counter type="COMPLEXITY" missed="1" covered="1"/>
      </method>
    </class>
    <class name="com/example/Helper" sourcefilename="Helper.java">
      <method name="help" desc="()V" line="3">
        <counter type="LINE" missed="0" covered="1"/>
        <counter type="COMPLEXITY" missed="0" covered="1"/>
      </method>
    </class>
    <sourcefile name="Widget.java">
      <line nr="5" mi="0" ci="4" mb="1" cb="1"/>
      <line nr="6" mi="0" ci="2" mb="0" cb="0"/>
    </sourcefile>
    <sourcefile name="Helper.java">
      <line nr="3" mi="0" ci="2" mb="0" cb="0"/>
    </sourcefile>
  </package>
</report>
EOF

# line 5 has instructions covered but neither of its branches taken, which
#  JaCoCo calls partly covered and lcov calls inconsistent:  a line with a
#  non-zero hit count all of whose branches were missed
cat > inconsistent.xml << 'EOF'
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE report PUBLIC "-//JACOCO//DTD Report 1.1//EN" "report.dtd">
<report name="inconsistent">
  <package name="com/example">
    <class name="com/example/Widget" sourcefilename="Widget.java">
      <method name="run" desc="()V" line="5">
        <counter type="BRANCH" missed="2" covered="0"/>
        <counter type="LINE" missed="0" covered="1"/>
        <counter type="COMPLEXITY" missed="2" covered="1"/>
      </method>
    </class>
    <sourcefile name="Widget.java">
      <line nr="5" mi="0" ci="3" mb="2" cb="0"/>
    </sourcefile>
  </package>
</report>
EOF

# the other complaint: function rather than branch data:
#  'dead' was never entered - its covered COMPLEXITY is 0 - but the
#  extent derived for it from its LINE counter is the two lines it missed, 6
#  and 10, and that reaches over line 8, which belongs to 'run' and is covered.
#  'run' has a taken branch so that this report, like the nominal one, has
#  branch data in it
cat > inconsistentfunc.xml << 'EOF'
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE report PUBLIC "-//JACOCO//DTD Report 1.1//EN" "report.dtd">
<report name="inconsistentfunc">
  <package name="com/example">
    <class name="com/example/Widget" sourcefilename="Widget.java">
      <method name="run" desc="()V" line="4">
        <counter type="BRANCH" missed="1" covered="1"/>
        <counter type="LINE" missed="0" covered="2"/>
        <counter type="COMPLEXITY" missed="1" covered="1"/>
      </method>
      <method name="dead" desc="()V" line="6">
        <counter type="LINE" missed="2" covered="0"/>
        <counter type="COMPLEXITY" missed="1" covered="0"/>
      </method>
    </class>
    <sourcefile name="Widget.java">
      <line nr="4" mi="0" ci="4" mb="1" cb="1"/>
      <line nr="6" mi="2" ci="0" mb="0" cb="0"/>
      <line nr="8" mi="0" ci="3" mb="0" cb="0"/>
      <line nr="10" mi="2" ci="0" mb="0" cb="0"/>
    </sourcefile>
  </package>
</report>
EOF

printf 'this is not XML\n' > notxml.xml

# the stub 'java'.  '$STUB_LOG' gets the command line, including the name
#  jacoco2lcov ran it by - which is the only way to see which java it chose -
#  '$STUB_REPORT' names the report to write, and '$STUB_STATUS'/'$STUB_SIGNAL'
#  make it fail on demand
cat > fakejava << 'EOF'
#!/bin/bash
echo "$0 $*" > ${STUB_LOG:-fakejava.log}
xml=
while [ $# -gt 0 ] ; do
    if [ "$1" == '--xml' ] ; then
        xml=$2
        shift
    fi
    shift
done
if [ "x$STUB_SIGNAL" != 'x' ] ; then
    kill -$STUB_SIGNAL $$
fi
if [ "x$STUB_STATUS" != 'x' ] ; then
    exit $STUB_STATUS
fi
if [ "x$xml" == 'x' ] ; then
    echo "stub java: no --xml argument"
    exit 1
fi
cp ${STUB_REPORT:-nominal.xml} $xml
EOF
chmod +x fakejava

# the three places jacoco2lcov looks for java when '--java' does not say which
#  one to use:  $JAVA_HOME/bin/java when there is one which can be run, and the
#  PATH otherwise
mkdir -p javahome/bin pathbin nojavahome nonexecjavahome/bin
cp fakejava javahome/bin/java
cp fakejava pathbin/java
cp fakejava nonexecjavahome/bin/java
chmod 000 nonexecjavahome/bin/java

# a jar and an execution data file which exist and cannot be read.  These are
#  the difference between 'there is nothing there' and 'there is something
#  there which is no use', which are separate messages
mkdir -p noreadhome/lib
printf 'not really a jar\n' > noread.jar
printf 'not really a jar\n' > noreadhome/lib/jacococli.jar
printf 'not really execution data\n' > noread.exec
chmod 000 noread.jar noreadhome/lib/jacococli.jar noread.exec

# an Eclipse/Maven plugin tree:  two plugins under one root, one in each of the
#  two layouts, plus a plugin root with no plugin in it and a plugin with
#  sources but no classes.  Between them the two plugins hold the sources the
#  fixture report names, so a '-p' run has to find both to translate anything
write_source plugins/pluginA/src/main/java/com/example/Widget.java 10
write_source plugins/pluginB/src/com/example/Helper.java 10
mkdir -p plugins/pluginA/target/classes plugins/pluginB/bin
mkdir -p emptyplugins/notaplugin
printf 'not a plugin either\n' > emptyplugins/notes.txt
mkdir -p noclassplugin/src/java
mkdir -p noreadplugins
chmod 000 noreadplugins

# a root directory for '-d':  a project laid out the Maven way, rather than the
#  Eclipse way this directory is laid out in, so that a run which searches for
#  the source and class directories says which of the two it searched.  Its
#  execution data is a directory of '.exec' files rather than a list of them,
#  which is what a build that writes one file per test run leaves behind, plus
#  a file which is not execution data and an empty directory
write_source droot/src/main/java/com/example/Widget.java 10
write_source droot/src/main/java/com/example/Helper.java 10
mkdir -p droot/target/classes droot/execdir/nested droot/emptyexec
printf 'not really a class file\n' > droot/target/classes/Widget.class
printf 'not really execution data\n' > droot/execdir/second.exec
printf 'not really execution data\n' > droot/execdir/nested/first.exec
printf 'notes, not execution data\n' > droot/execdir/notes.txt

# ---------------------------------------------------------------------------
# the harness
# ---------------------------------------------------------------------------

# run <label> <expected exit status> <args>... -- run jacoco2lcov, keeping its
#  output in '<label>.log'.  Returns success when the exit status was the
#  expected one, so a caller which wants to look at the result can do that only
#  when the run went the way it was supposed to
run()
{
    local label=$1
    local expect=$2
    shift 2

    echo "$label: jacoco2lcov $*"
    $COVER ${EXEC_COVER} $JACOCO2LCOV_TOOL "$@" > $label.log 2>&1
    local rc=$?
    if [ $rc != $expect ] ; then
        fail $label "expected exit status $expect, got $rc:"
        cat $label.log
        return 1
    fi
    return 0
}

# expect_log <label> <pattern> -- the run said this
expect_log()
{
    if ! grep -q -- "$2" $1.log ; then
        fail $1 "expected '$2' in the output:"
        cat $1.log
    fi
}

# reject_log <label> <pattern> -- and did not say this
reject_log()
{
    if grep -q -- "$2" $1.log ; then
        fail $1 "did not expect '$2' in the output:"
        cat $1.log
    fi
}

# expect_data <label> <file> <pattern> -- the generated .info says this
expect_data()
{
    if ! grep -q -- "$3" $2 ; then
        fail $1 "expected '$3' in $2:"
        cat $2
    fi
}

# reject_data <label> <file> <pattern> -- and does not say this
reject_data()
{
    if grep -q -- "$3" $2 ; then
        fail $1 "did not expect '$3' in $2:"
        cat $2
    fi
}

# canonical_info <file> -- the coverage data in <file>, in an order which does
#  not depend on who wrote the file:  one section per source file, sorted, with
#  the coverpoints inside it sorted too, and the test name dropped.  Two files
#  which say the same thing about the same code produce the same text here.
#  Cmparison against xml2lcov's own output has to be rewritten by lcov's writer
#  so it gets the same order as jacoco2lcov produces.
canonical_info()
{
    perl -e 'my (%rec, $sf, @body);
             while (<>) {
                 next if /^TN:/;
                 if (/^SF:/) { $sf = $_; @body = (); next }
                 if (/^end_of_record/) { $rec{$sf} = join("", sort(@body)); next }
                 push(@body, $_);
             }
             foreach my $f (sort(keys(%rec))) { print($f, $rec{$f}) }' "$1"
}

# undocumented_options <label> -- the entries in the 'Tool options:' section of
#  the usage message which do not say whether the option is optional or
#  required, or do not say what it defaults to.  Checked this way rather than
#  by matching the text, which is prose and gets reworded:  what has to hold is
#  that every option says both of those things, not that it says them in any
#  particular words.  '--help' itself is exempt - it has no default
undocumented_options()
{
    perl -e '
        my ($in_section, $option, $text);
        my @undocumented;
        sub check
        {
            return unless defined($option);
            return if $option =~ /--help/;
            push(@undocumented, "$option: no optional/required marking")
                unless $text =~ /Optional|Required/;
            push(@undocumented, "$option: no default")
                unless $text =~ /Default:/;
        }
        while (<>) {
            if (!$in_section) {
                $in_section = 1 if /^Tool options:/;
                next;
            }
            last if /^Common options:/;
            #  an option entry starts with the option names, indented;  two of
            #   them in a row share the description which follows
            if (/^ +--?[a-zA-Z]/) {
                if (defined($option) && $text !~ /\S/) {
                    $option .= " $_";
                } else {
                    check();
                    ($option, $text) = ($_, "");
                }
                $option =~ s/\s+/ /g;
                $option =~ s/^ | $//g;
                next;
            }
            $text .= $_ if defined($option);
        }
        check();
        print(map("$_\n", @undocumented));
    ' < $1.log
}

# expect_java <label> <expected command line> -- the stub 'java' was run with
#  exactly this.  The temporary report name is replaced, because it is below the
#  temporary directory lcovutil made, whose name is different on every run -
#  which is the point of it.  A report which '--xml' asked to keep is named
#  something else, so it survives
expect_java()
{
    local actual=`sed -e 's,--xml [^ ]*/jacoco\.xml,--xml TMPXML,' fakejava.log`
    if [ "$actual" != "$2" ] ; then
        fail $1 "java command line is
  '$actual'
rather than
  '$2'"
    fi
}

export STUB_LOG=fakejava.log
export STUB_REPORT STUB_STATUS STUB_SIGNAL
# jacoco2lcov reads all three of these, so which java and which jacococli.jar a
#  run uses has to be this test's decision rather than the environment's.
#  'LCOV_ASSUME_WINDOWS' and 'LCOV_DRIVE_MOUNT' are the test hooks
#  sections 15 and 16 use, and belong to those sections alone
unset JACOCO_HOME JACOCOCLI_JAR JAVA_HOME LCOV_ASSUME_WINDOWS \
    LCOV_DRIVE_MOUNT

# ---------------------------------------------------------------------------
# 1. --help and the usage errors
# ---------------------------------------------------------------------------

if run help 0 --help ; then
    expect_log help 'Usage: jacoco2lcov'
    expect_log help 'plugin-directory'
    #  every option says whether it is optional or required and what it
    #   defaults to
    undocumented=`undocumented_options help`
    if [ -n "$undocumented" ] ; then
        fail help "options which the usage message does not fully document:
$undocumented"
    fi
fi

if run noargs 1 ; then
    expect_log noargs 'no JaCoCo execution data file named'
    expect_log noargs 'Usage: jacoco2lcov'
fi

if run noexec 1 -s src -c bin nosuchfile.exec ; then
    expect_log noexec "'nosuchfile.exec' is not a readable file"
fi

# an .exec file which is there and cannot be read is the same complaint.
#  Skipped when the test is run by a user who can read a file whatever its mode
#  says
if [ -r noread.exec ] ; then
    echo "noread.exec is readable anyway - skipping"
elif run noreadexec 1 -s src -c bin noread.exec ; then
    expect_log noreadexec "'noread.exec' is not a readable file"
fi

if run noclass 1 -s src test.exec ; then
    expect_log noclass 'no class files named'
fi

if run nosource 1 -c bin test.exec ; then
    expect_log nosource 'no source directory named'
fi

# an option written in a way Getopt::Long cannot use stops the run:  it is
#  neither an option this can act on nor the name of an execution data file, and
#  guessing which was meant would run the wrong translation.  '-o' takes a value
#  and has none here;  '--verbose' takes none and was given one
if run novalue 1 -s src -c bin test.exec -o ; then
    expect_log novalue 'requires an argument'
    expect_log novalue "Use 'jacoco2lcov --help'"
fi

if run unwantedvalue 1 -s src -c bin --verbose=3 test.exec ; then
    expect_log unwantedvalue 'does not take an argument'
    expect_log unwantedvalue "Use 'jacoco2lcov --help'"
fi

# an option which is nobody's is an error too:  every option jacoco2lcov
#  understands is either its own or one of the common ones, and there is nothing
#  left for it to be forwarded to
if run unknownopt 1 -s src -c bin --nosuchoption test.exec ; then
    expect_log unknownopt 'Unknown option'
    expect_log unknownopt "Use 'jacoco2lcov --help'"
fi

# a class location which is not there is a warning:  a build tree can
#  legitimately be missing one of several - and JaCoCo doesn't complain about
#  ones it did not find.  A source directory which is not there is the common
#  '--source-directory' option's own 'path' error - the same error, and the same
#  way of accepting it, as in every other tool of the suite
if run missingdirs 0 -o missingdirs.info -s src -s nosuchdir -c bin \
       -c nosuchbin --ignore-errors=path --jar $JAR --java ./fakejava \
       test.exec ; then
    expect_log missingdirs "source directory 'nosuchdir' is not a directory"
    expect_log missingdirs "class location 'nosuchbin' does not exist"
    expect_data missingdirs missingdirs.info '^SF:src/com/example/Widget.java$'
fi

# and without that, it stops the run
if run badsourcedir 2 -o badsourcedir.info -s nosuchdir -c bin --jar $JAR \
       --java ./fakejava test.exec ; then
    expect_log badsourcedir "source directory 'nosuchdir' is not a directory"
fi

# ---------------------------------------------------------------------------
# 2. finding jacococli.jar
# ---------------------------------------------------------------------------

if run nojar 1 -s src -c bin test.exec ; then
    expect_log nojar 'unable to find jacococli.jar'
fi

if run badjar 1 -s src -c bin --jar nosuch.jar test.exec ; then
    expect_log badjar "'nosuch.jar' is not a readable file"
fi

export JACOCOCLI_JAR=nosuch.jar
if run badenvjar 1 -s src -c bin test.exec ; then
    expect_log badenvjar "JACOCOCLI_JAR names 'nosuch.jar'"
fi

# a jar which is there and cannot be read, from each of the two places it can
#  be named
if [ -r noread.jar ] ; then
    echo "noread.jar is readable anyway - skipping"
else
    JACOCOCLI_JAR=noread.jar
    if run noreadenvjar 1 -s src -c bin test.exec ; then
        expect_log noreadenvjar "JACOCOCLI_JAR names 'noread.jar'"
    fi
    unset JACOCOCLI_JAR
    if run noreadjar 1 -s src -c bin --jar noread.jar test.exec ; then
        expect_log noreadjar "'noread.jar' is not a readable file"
    fi
    # a JACOCO_HOME whose jar cannot be read holds no usable jar
    export JACOCO_HOME=noreadhome
    if run noreadhome 1 -s src -c bin test.exec ; then
        expect_log noreadhome 'no jacococli.jar found under the JACOCO_HOME'
    fi
    unset JACOCO_HOME
fi
export JACOCOCLI_JAR
JACOCOCLI_JAR=$JAR
if run envjar 0 -o envjar.info -s src -c bin --java ./fakejava test.exec ; then
    expect_java envjar "./fakejava -jar $JAR report test.exec --classfiles bin --sourcefiles src --xml TMPXML"
fi
unset JACOCOCLI_JAR

export JACOCO_HOME=emptyhome
if run emptyhome 1 -s src -c bin test.exec ; then
    expect_log emptyhome 'no jacococli.jar found under the JACOCO_HOME'
fi

JACOCO_HOME=libhome
if run libhome 0 -o libhome.info -s src -c bin --java ./fakejava test.exec ; then
    expect_java libhome "./fakejava -jar libhome/lib/jacococli.jar report test.exec --classfiles bin --sourcefiles src --xml TMPXML"
fi

JACOCO_HOME=jarhome
if run jarhome 0 -o jarhome.info -s src -c bin --java ./fakejava test.exec ; then
    expect_java jarhome "./fakejava -jar jarhome/jacococli.jar report test.exec --classfiles bin --sourcefiles src --xml TMPXML"
fi
unset JACOCO_HOME

# ---------------------------------------------------------------------------
# 3. the java command line, and 4. the coverage type defaults
# ---------------------------------------------------------------------------

# note the single-dash '-jar', which is how the jacococli and jacoco2lcov jars
#  are invoked and so what a user is likely to type
if run nominal 0 -o nominal.info -t mytest -s src -c bin -c extra/classes.jar \
       -jar $JAR --java ./fakejava test.exec test.exec ; then
    expect_java nominal "./fakejava -jar $JAR report test.exec test.exec --classfiles bin --classfiles extra/classes.jar --sourcefiles src --xml TMPXML"
    expect_data nominal nominal.info '^TN:mytest$'
    expect_data nominal nominal.info '^SF:src/com/example/Widget.java$'
    expect_data nominal nominal.info '^SF:src/com/example/Helper.java$'
    expect_data nominal nominal.info '^BRDA:5,0,0,1$'
    expect_data nominal nominal.info '^BRDA:5,0,1,0$'
    expect_data nominal nominal.info '^FNA:0,1,com.example.Widget.run()V$'
    # the intermediate files were temporary
    if [ -e jacoco.xml ] ; then
        fail nominal "the intermediate XML report was left behind"
    fi
fi

# a coverage type which is off is dropped as the translation is read back in.
#  Both are on by default here - the nominal case above has the 'BRDA:' and the
#  'FNA:' to verify - so each of these turns one of them off again
if run nobranch 0 -o nobranch.info -s src -c bin -jar $JAR \
       --java ./fakejava --no-branch-coverage test.exec ; then
    expect_data nobranch nobranch.info '^DA:5,1$'
    expect_data nobranch nobranch.info 'com.example.Widget.run()V'
    reject_data nobranch nobranch.info '^BRDA:'
fi

if run nofunc 0 -o nofunc.info -s src -c bin -jar $JAR \
       --java ./fakejava --no-function-coverage test.exec ; then
    expect_data nofunc nofunc.info '^BRDA:5,0,0,1$'
    reject_data nofunc nofunc.info 'com.example.Widget.run()V'
fi

# and the config file settings the same options set are the same
if run rcnobranch 0 -o rcnobranch.info -s src -c bin -jar $JAR \
       --java ./fakejava --rc branch_coverage=0 test.exec ; then
    expect_data rcnobranch rcnobranch.info '^DA:5,1$'
    expect_data rcnobranch rcnobranch.info 'com.example.Widget.run()V'
    reject_data rcnobranch rcnobranch.info '^BRDA:'
fi

if run rcnofunc 0 -o rcnofunc.info -s src -c bin -jar $JAR \
       --java ./fakejava --rc function_coverage=0 test.exec ; then
    expect_data rcnofunc rcnofunc.info '^BRDA:5,0,0,1$'
    reject_data rcnofunc rcnofunc.info 'com.example.Widget.run()V'
fi

# ---------------------------------------------------------------------------
# 5. the common options, and 6. what names an .exec file
# ---------------------------------------------------------------------------

# the common options are applied to the translated data here, by the same code
#  which applies them to a .info file from any other source - so what this has
#  to show is that they reach it.  '--exclude' drops a file, and the branch data
#  survives, which is jacoco2lcov's coverage type default at work
if run exclude 0 -o exclude.info -s src -c bin -jar $JAR --java ./fakejava \
       --exclude='*/Helper.java' test.exec ; then
    expect_data exclude exclude.info '^SF:src/com/example/Widget.java$'
    reject_data exclude exclude.info 'Helper.java'
    expect_data exclude exclude.info '^BRDA:5,0,0,1$'
fi

# the value of such an option may be written as a separate argument:
#  it is not confused with an .exec file name, and the result is the run above
if run splitvalue 0 -o splitvalue.info -s src -c bin -jar $JAR \
       --java ./fakejava --exclude '*/Helper.java' test.exec ; then
    expect_data splitvalue splitvalue.info '^SF:src/com/example/Widget.java$'
    reject_data splitvalue splitvalue.info 'Helper.java'
fi

# a pattern which matched nothing is reported, and a filter which removed
#  nothing is summarized:  both belong to the common option handling, and both
#  have to survive the fact that the data came from a translation.  An unused
#  pattern is an error of its own, so this asks for it to be ignored - which
#  also shows that the common '--ignore-errors' handles errors raised after the
#  translation as well as during it
if run unusedpattern 0 -o unusedpattern.info -s src -c bin -jar $JAR \
       --java ./fakejava --exclude='*/NoSuchFile.java' --filter=branch \
       --ignore-errors=unused test.exec ; then
    expect_log unusedpattern 'NoSuchFile.java'
    expect_data unusedpattern unusedpattern.info '^SF:src/com/example/Widget.java$'
fi

# '--comment' is a common option whose effect is visible in the file itself
if run comment 0 -o comment.info -s src -c bin -jar $JAR --java ./fakejava \
       --comment 'translated from JaCoCo' test.exec ; then
    expect_data comment comment.info 'translated from JaCoCo'
fi

# every argument which is not an option names an execution data file, whatever
#  it is called:  '.exec' is a convention, and nothing here depends on it.  A
#  common option may be written after it, and '--forget-test-names' is one whose
#  effect can be seen in spite of '-t'
if run commonopts 0 -o commonopts.info -t mytest -s src -c bin -jar $JAR \
       --java ./fakejava -v plaindata --forget-test-names ; then
    expect_java commonopts "./fakejava -jar $JAR report plaindata --classfiles bin --sourcefiles src --xml TMPXML"
    expect_data commonopts commonopts.info '^TN:$'
    reject_data commonopts commonopts.info '^TN:mytest$'
fi

# '--' ends the options, and what follows it is execution data like every other
#  argument which is not an option - so an option written after it is looked for
#  as a file and not found
if run endofoptions 1 -o endofoptions.info -s src -c bin -jar $JAR \
       --java ./fakejava -- --forget-test-names test.exec ; then
    expect_log endofoptions "'--forget-test-names' is not a readable file"
fi

# ---------------------------------------------------------------------------
# 7. a run which asks nothing of the data, and --xml
# ---------------------------------------------------------------------------

# with nothing asked of it, the answer is the translation and nothing else -
#  which is checked against a hand-run xml2lcov on the report '--xml' kept.
#  '-v' is there to see which commands ran:  those two and no other
if run plainrun 0 -o plainrun.info -t mytest -s src -c bin -jar $JAR \
       --java ./fakejava -v --xml kept.xml test.exec ; then
    if [ ! -f kept.xml ] ; then
        fail plainrun "'--xml kept.xml' did not keep the XML report"
    elif ! diff nominal.xml kept.xml > /dev/null ; then
        fail plainrun "the kept XML report is not the one JaCoCo wrote"
    fi
    eval ${PYCOVER} $XML2LCOV_TOOL --format jacoco -o direct.info -t mytest \
        -s src kept.xml
    if [ 0 != $? ] ; then
        fail plainrun "xml2lcov failed on the kept report"
    elif ! diff <(canonical_info direct.info) \
                <(canonical_info plainrun.info) ; then
        fail plainrun "the answer is not what xml2lcov wrote"
    fi
    #  and the test name '-t' asked for survives the trip through the reader
    expect_data plainrun plainrun.info '^TN:mytest$'
fi

# ---------------------------------------------------------------------------
# 8. -p, the Eclipse/Maven plugin shorthand
# ---------------------------------------------------------------------------

# 'plugins' is not a plugin itself - it has no sources - so its children are
#  the plugins, and each contributes the conventional directories it has.
#  pluginA is in the Maven layout, so its source root is 'src/main/java' and
#  not the 'src' above it;  pluginB is in the Eclipse layout, where 'src' is
#  the source root
if run plugins 0 -o plugins.info -p plugins -jar $JAR --java ./fakejava \
       test.exec ; then
    expect_java plugins "./fakejava -jar $JAR report test.exec --classfiles plugins/pluginA/target/classes --classfiles plugins/pluginB/bin --sourcefiles plugins/pluginA/src/main/java --sourcefiles plugins/pluginB/src --xml TMPXML"
    expect_data plugins plugins.info '^SF:plugins/pluginA/src/main/java/com/example/Widget.java$'
    expect_data plugins plugins.info '^SF:plugins/pluginB/src/com/example/Helper.java$'
fi

# '-p' can equally name one plugin directly.  Only Widget.java is reachable
#  from pluginA, so Helper.java is dropped and the run is still a success
if run oneplugin 0 -o oneplugin.info -p plugins/pluginA -jar $JAR \
       --java ./fakejava test.exec ; then
    expect_java oneplugin "./fakejava -jar $JAR report test.exec --classfiles plugins/pluginA/target/classes --sourcefiles plugins/pluginA/src/main/java --xml TMPXML"
    expect_log oneplugin '1 source file(s) not found in the search path'
fi

# a '-p' which finds nothing is a warning and then the ordinary complaint about
#  having nothing to work with.  Note that naming it is not the same as naming
#  nothing at all:  the current directory is searched only when the command line
#  said nothing about where to look, and this one said 'emptyplugins'
if run noplugin 1 -p emptyplugins -jar $JAR --java ./fakejava test.exec ; then
    expect_log noplugin "no Eclipse/Maven plugin with sources found in 'emptyplugins'"
    expect_log noplugin 'no class files named'
    reject_log noplugin 'looking for source and class directories'
fi

if run noclassplugin 1 -p noclassplugin -jar $JAR --java ./fakejava \
       test.exec ; then
    expect_log noclassplugin "no class directory found in plugin directory 'noclassplugin'"
    expect_log noclassplugin 'no class files named'
fi

if run badplugin 1 -p test.exec -jar $JAR --java ./fakejava test.exec ; then
    expect_log badplugin "'test.exec' is not a directory"
fi

# a plugin root which cannot be read is the same warning:  there is nothing in
#  it as far as this can tell.  Skipped when the test is run by a user who can
#  read a directory whatever its mode says
if [ -r noreadplugins ] ; then
    echo "noreadplugins is readable anyway - skipping"
elif run noreadplugins 1 -p noreadplugins -c bin -jar $JAR --java ./fakejava \
         test.exec ; then
    expect_log noreadplugins "no Eclipse/Maven plugin with sources found in 'noreadplugins'"
fi

# with none of '-s', '-c' and '-p' named, the current directory is searched the
#  way '-p .' would search it.  This one holds 'src' and 'bin' - the Eclipse
#  layout - so those are what the run uses, without the './' the search finds
#  them under
if run defaultdirs 0 -o defaultdirs.info -jar $JAR --java ./fakejava \
       test.exec ; then
    expect_log defaultdirs "no '-s', '-c' or '-p' option: looking for source and class directories in the current directory"
    expect_java defaultdirs "./fakejava -jar $JAR report test.exec --classfiles bin --sourcefiles src --xml TMPXML"
    expect_data defaultdirs defaultdirs.info '^SF:src/com/example/Widget.java$'
fi

# ---------------------------------------------------------------------------
# 9. a subcommand which fails
# ---------------------------------------------------------------------------

STUB_STATUS=3
if run javastatus 1 -o javastatus.info -s src -c bin -jar $JAR \
       --java ./fakejava test.exec ; then
    expect_log javastatus 'the JaCoCo XML report step returned exit status 3'
fi
STUB_STATUS=

STUB_SIGNAL=TERM
if run javasignal 1 -o javasignal.info -s src -c bin -jar $JAR \
       --java ./fakejava test.exec ; then
    expect_log javasignal 'the JaCoCo XML report step terminated by signal 15'
fi
STUB_SIGNAL=

if run nojava 1 -o nojava.info -s src -c bin -jar $JAR \
       --java ./nosuchjava test.exec ; then
    expect_log nojava "unable to execute './nosuchjava'"
fi

# an executable which is not one is a jacoco2lcov error rather than a failure
#  of the step, because it is found before anything is run - whether the name
#  is not a file at all, or is a file which cannot be run
if run badtool 1 -o badtool.info -s src -c bin -jar $JAR --java ./fakejava \
       --xml2lcov src test.exec ; then
    expect_log badtool "'src' is not an executable file"
    expect_log badtool "use '--xml2lcov'"
fi

STUB_REPORT=notxml.xml
if run notxml 1 -o notxml.info -s src -c bin -jar $JAR --java ./fakejava \
       test.exec ; then
    expect_log notxml 'the xml2lcov translation step returned exit status 1'
fi
STUB_REPORT=

# ---------------------------------------------------------------------------
# 10. the 'inconsistent' hint
# ---------------------------------------------------------------------------

# reading the translation back in is what objects to the derived data, and the
#  hint is jacoco2lcov's:  the error itself says nothing about JaCoCo, so
#  something has to say why a JaCoCo translation is the data most likely to
#  produce it
STUB_REPORT=inconsistent.xml
if run inconsistent 1 -o inconsistent.info -s src -c bin -jar $JAR \
       --java ./fakejava test.exec ; then
    expect_log inconsistent 'inconsistent'
    expect_log inconsistent "use '--ignore-errors=inconsistent'"
    #  and nothing was written:  the run failed
    if [ -f inconsistent.info ] ; then
        fail inconsistent 'an output file was written by a failed run'
    fi
fi

# and the option the hint names works, spelled the way the hint spells it
if run ignore 0 -o ignore.info -s src -c bin -jar $JAR --java ./fakejava \
       --ignore-errors=inconsistent test.exec ; then
    expect_data ignore ignore.info '^DA:5,1$'
    expect_data ignore ignore.info '^BRDA:5,0,0,0$'
fi

# function data disagreeing with line data gets the same hint:  the derived
#  extent of a method which was never entered reaches over a covered line
STUB_REPORT=inconsistentfunc.xml
if run inconsistentfunc 1 -o inconsistentfunc.info -s src -c bin -jar $JAR \
       --java ./fakejava test.exec ; then
    expect_log inconsistentfunc 'inconsistent'
    expect_log inconsistentfunc 'com.example.Widget.dead()V'
    expect_log inconsistentfunc 'line 8'
    expect_log inconsistentfunc "use '--ignore-errors=inconsistent'"
    if [ -f inconsistentfunc.info ] ; then
        fail inconsistentfunc 'an output file was written by a failed run'
    fi
fi

# accepting this one marks the function hit, which is the opposite of what
#  JaCoCo said about it - the behaviour the man pages warn about
if run ignorefunc 0 -o ignorefunc.info -s src -c bin -jar $JAR --java ./fakejava \
       --ignore-errors=inconsistent test.exec ; then
    expect_data ignorefunc ignorefunc.info '^FNA:1,1,com.example.Widget.dead()V$'
    expect_data ignorefunc ignorefunc.info '^FNH:2$'
fi
STUB_REPORT=

# ---------------------------------------------------------------------------
# 11. which java gets run
# ---------------------------------------------------------------------------

# every case above named the stub with '--java'.  Without that option,
#  jacoco2lcov runs $JAVA_HOME/bin/java when that is an executable and
#  otherwise leaves the plain name 'java' for the PATH to resolve - so put the
#  stub on the PATH as well, where the fallback can find it.  The stub logs the
#  name it was run by, which is how each of these says which java was chosen
SAVED_PATH=$PATH
export PATH=`pwd`/pathbin:$PATH

if run pathjava 0 -o pathjava.info -s src -c bin -jar $JAR test.exec ; then
    expect_java pathjava "`pwd`/pathbin/java -jar $JAR report test.exec --classfiles bin --sourcefiles src --xml TMPXML"
fi

# a JAVA_HOME with no java under it, and one whose java cannot be run:  both
#  fall back to the PATH rather than failing, because JAVA_HOME is set by
#  whoever installed the JDK and not by whoever is running jacoco2lcov, so a
#  stale one should not stop a run which has a usable java anyway
JAVA_HOME=`pwd`/nojavahome
export JAVA_HOME
if run nojavahome 0 -o nojavahome.info -s src -c bin -jar $JAR test.exec ; then
    expect_java nojavahome "`pwd`/pathbin/java -jar $JAR report test.exec --classfiles bin --sourcefiles src --xml TMPXML"
fi

JAVA_HOME=`pwd`/nonexecjavahome
if [ -x nonexecjavahome/bin/java ] ; then
    echo "skipping the 'nonexecjava' case - running as root?"
elif run nonexecjava 0 -o nonexecjava.info -s src -c bin -jar $JAR test.exec ; then
    expect_java nonexecjava "`pwd`/pathbin/java -jar $JAR report test.exec --classfiles bin --sourcefiles src --xml TMPXML"
fi

JAVA_HOME=`pwd`/javahome
if run javahome 0 -o javahome.info -s src -c bin -jar $JAR test.exec ; then
    expect_java javahome "`pwd`/javahome/bin/java -jar $JAR report test.exec --classfiles bin --sourcefiles src --xml TMPXML"
fi
unset JAVA_HOME
export PATH=$SAVED_PATH

# ---------------------------------------------------------------------------
# 12. --verbose and --keep-going
# ---------------------------------------------------------------------------

# '--verbose' prints each command before it runs it, which is the only way to
#  see what was asked of xml2lcov;  '--keep-going' reaches it, because it is a
#  separate process and an lcovrc or a command line which turned the error
#  handling off has to mean the same thing there
if run verbose 0 -o verbose.info -s src -c bin -jar $JAR --java ./fakejava \
       -v --keep-going test.exec ; then
    expect_log verbose "./fakejava -jar $JAR report test.exec"
    expect_log verbose "xml2lcov --format jacoco -o .*\.info -s src -v --keep-going"
    expect_log verbose "Wrote LCOV data to 'verbose.info'"
fi

# '-k' is the short form, which the common option does not have:  'lcov -k' is
#  '--kernel-directory', so this one is jacoco2lcov's own and has to reach the
#  same place
if run keepgoing 0 -o keepgoing.info -s src -c bin -jar $JAR \
       --java ./fakejava -v -k test.exec ; then
    expect_log keepgoing "xml2lcov --format jacoco -o .*\.info -s src -v --keep-going"
fi

# and the other way about:  the setting can be turned on as well as off, and
#  when it is on there is nothing to pass along - the step is to stop at the
#  first error, which is what it does with nothing said to it
if run stoponerror 0 -o stoponerror.info -s src -c bin -jar $JAR \
       --java ./fakejava -v --rc stop_on_error=1 test.exec ; then
    expect_log stoponerror "xml2lcov --format jacoco -o .*\.info -s src -v"
    reject_log stoponerror '\-\-keep-going'
fi

# ---------------------------------------------------------------------------
# 13. -d, the root directory
# ---------------------------------------------------------------------------

# a '-d' run works in another directory, so the things which belong to this one
#  - the stub and the report it writes - are named by absolute path from here on
SAVED_STUB_LOG=$STUB_LOG
export STUB_LOG=`pwd`/fakejava.log
export STUB_REPORT=`pwd`/nominal.xml
FAKEJAVA=`pwd`/fakejava
DROOT=`pwd`/droot

# '-d' says where to work:  the source, class and execution data paths are taken
#  relative to it, and so is the output file.  'execdir' is a directory of
#  execution data rather than a file, which stands for the '.exec' files below
#  it, sorted - and for nothing else in it
if run droot 0 -d droot -o d_out.info -s src/main/java -c target/classes \
       -jar $JAR --java $FAKEJAVA -v execdir ; then
    expect_log droot "working in root directory '$DROOT'"
    expect_java droot "$FAKEJAVA -jar $JAR report execdir/nested/first.exec execdir/second.exec --classfiles target/classes --sourcefiles src/main/java --xml TMPXML"
    if [ ! -f droot/d_out.info ] ; then
        fail droot 'the output file was not written below the root directory'
    else
        expect_data droot droot/d_out.info '^SF:src/main/java/com/example/Widget.java$'
    fi
fi

# an absolute path below the root directory is recorded relative to it, which is
#  what makes the names in the result line up with the rest of your coverage
#  data.  The output file is named absolutely here, which leaves it where it was
#  asked for rather than below the root
if run dabsolute 0 -d droot -o `pwd`/dabsolute.info -s $DROOT/src/main/java \
       -c $DROOT/target/classes -jar $JAR --java $FAKEJAVA \
       execdir/second.exec ; then
    expect_java dabsolute "$FAKEJAVA -jar $JAR report execdir/second.exec --classfiles target/classes --sourcefiles src/main/java --xml TMPXML"
    expect_data dabsolute dabsolute.info '^SF:src/main/java/com/example/Widget.java$'
fi

# an absolute path outside the root directory is left as it is:  no name
#  relative to the root would be any clearer than the absolute one.  This one
#  names this directory's own sources, which are the same files
if run doutside 0 -d droot -o `pwd`/doutside.info -s `pwd`/src \
       -c target/classes -jar $JAR --java $FAKEJAVA execdir/second.exec ; then
    expect_java doutside "$FAKEJAVA -jar $JAR report execdir/second.exec --classfiles target/classes --sourcefiles `pwd`/src --xml TMPXML"
    expect_data doutside doutside.info "^SF:`pwd`/src/com/example/Widget.java\$"
fi

# the search which '-p .' would do happens in the root directory too, which is
#  what this one is laid out the Maven way to show:  the directories it finds
#  are the root's and not this directory's
if run ddefault 0 -d droot -o ddefault.info -jar $JAR --java $FAKEJAVA \
       execdir/second.exec ; then
    expect_log ddefault "looking for source and class directories in the current directory"
    expect_java ddefault "$FAKEJAVA -jar $JAR report execdir/second.exec --classfiles target/classes --sourcefiles src/main/java --xml TMPXML"
fi

# a tool named without a directory is looked up on the PATH, which means the
#  same thing from any directory, so '-d' leaves such a name alone.  A relative
#  name with a directory in it is pinned down before the move instead - which is
#  why the cases above could name the stub as they did
SAVED_PATH=$PATH
export PATH=`pwd`/pathbin:$PATH
if run dpathjava 0 -d droot -o dpathjava.info -s src/main/java \
       -c target/classes -jar $JAR --java java execdir/second.exec ; then
    expect_java dpathjava "`pwd`/pathbin/java -jar $JAR report execdir/second.exec --classfiles target/classes --sourcefiles src/main/java --xml TMPXML"
fi
export PATH=$SAVED_PATH

if run dbadroot 1 -d nosuchdir -s src -c bin -jar $JAR --java $FAKEJAVA \
       test.exec ; then
    expect_log dbadroot "root directory 'nosuchdir' is not a directory"
fi

# a root directory which is one and cannot be entered.  Skipped when the test is
#  run by a user who can enter it anyway
if [ -x noreadplugins ] ; then
    echo "noreadplugins can be entered anyway - skipping"
elif run dnoenter 1 -d noreadplugins -s src -c bin -jar $JAR --java $FAKEJAVA \
         test.exec ; then
    expect_log dnoenter 'unable to work in root directory'
fi

# a directory of execution data with no '.exec' file below it is a warning, and
#  then the ordinary complaint about having nothing to translate
if run dnoexec 1 -d droot -s src/main/java -c target/classes -jar $JAR \
       --java $FAKEJAVA emptyexec ; then
    expect_log dnoexec "no '.exec' file found under the JaCoCo data directory 'emptyexec'"
    expect_log dnoexec 'no JaCoCo execution data file named'
fi

export STUB_LOG=$SAVED_STUB_LOG
STUB_REPORT=

# ---------------------------------------------------------------------------
# 14. the path the tool was invoked by
# ---------------------------------------------------------------------------

# jacoco2lcov finds the tools it runs beside itself, and used to name its
#  temporary directory after itself, so both of those depend on making sense of
#  the path it was invoked by.  That path is not necessarily written in the path
#  syntax of the perl which is running it:  a git-bash, MSYS or Cygwin perl has
#  Unix path semantics and is handed a Windows path, a drive letter and
#  backslashes, which neither FindBin nor basename() recognizes as one.  Such a
#  name is a legal file name here, so a link named that way asks the same
#  questions here that the failure asked there - is the tool which gets run the
#  one beside the script rather than one beside the name it was called by, and
#  does the name it was called by stay out of everything else.
#  'JACOCO2LCOV_TOOL' is what the harness runs, so it is what says how to invoke
#  the tool.  Coverage is turned off for these runs:  Devel::Cover records the
#  data under the path perl read the script from, and a second path to the same
#  script would be a second file in the coverage database
SAVED_JACOCO2LCOV_TOOL=$JACOCO2LCOV_TOOL
SAVED_COVER=$COVER
REALTOOL=`readlink -f $JACOCO2LCOV_TOOL`
REALBIN=`dirname $REALTOOL`
WINNAME='linkdir/S:\mtkoss\win\bin\jacoco2lcov'
mkdir -p linkdir
ln -s $REALTOOL linkdir/jacoco2lcov
ln -s $REALTOOL "$WINNAME"
COVER=

# through a link in a directory which holds nothing else:  the xml2lcov which
#  runs is the one installed beside the script, because that is what 'installed
#  next to jacoco2lcov' means - there is nothing beside the link
JACOCO2LCOV_TOOL=linkdir/jacoco2lcov
if run linked 0 -o linked.info -s src -c bin -jar $JAR --java ./fakejava -v \
       test.exec ; then
    expect_log linked "$REALBIN/xml2lcov --format jacoco"
    expect_java linked "./fakejava -jar $JAR report test.exec --classfiles bin --sourcefiles src --xml TMPXML"
fi

# through a link named the way a Windows path is written.  The run works, the
#  tool beside the script is the one which runs, and the temporary report is
#  below a directory named after the script - 'expect_java' knows what that name
#  looks like and would not recognize one built out of the link's name
JACOCO2LCOV_TOOL=$WINNAME
if run windowsname 0 -o windowsname.info -s src -c bin -jar $JAR \
       --java ./fakejava -v test.exec ; then
    expect_log windowsname "$REALBIN/xml2lcov --format jacoco"
    expect_java windowsname "./fakejava -jar $JAR report test.exec --classfiles bin --sourcefiles src --xml TMPXML"
    #  nothing anywhere in the output came from the name it was called by
    reject_log windowsname 'S:'
    expect_data windowsname windowsname.info '^SF:src/com/example/Widget.java$'
fi

# and the name in the usage message is the script's own name, which is the name
#  the reader can type again - not whatever the caller happened to write
if run windowshelp 0 --help ; then
    expect_log windowshelp '^Usage: jacoco2lcov '
    reject_log windowshelp 'S:'
fi

JACOCO2LCOV_TOOL=$SAVED_JACOCO2LCOV_TOOL
COVER=$SAVED_COVER

# ---------------------------------------------------------------------------
# 15. finding the tools to run on Windows
# ---------------------------------------------------------------------------

# On Windows, perl's '-x' answers from the file name extension rather than from
#  any permission, so an extensionless file is never executable there - and none
#  of the tools jacoco2lcov runs has an extension in an LCOV installation.  So
#  jacoco2lcov prefers a sibling with an extension Windows can run, and
#  otherwise runs the file it found anyway.  'LCOV_ASSUME_WINDOWS' is the
#  test hook which reaches that decision from here;  what a run which reached it
#  did is visible in which command it ran, or failed to run
export LCOV_ASSUME_WINDOWS=1

# a '.bat' beside the script is what an installation which wrapped the script
#  for Windows leaves, and the wrapper is the thing to run.  This one forwards to
#  the real xml2lcov, so the whole translation runs through it
XML2LCOV=`readlink -f ${XML2LCOV_TOOL}`
mkdir -p wintools
printf 'not an executable file\n' > wintools/xml2lcov
cat > wintools/xml2lcov.bat << EOF
#!/bin/bash
exec $XML2LCOV "\$@"
EOF
chmod 755 wintools/xml2lcov.bat
if run winbat 0 -o winbat.info -s src -c bin -jar $JAR --java ./fakejava -v \
       --xml2lcov wintools/xml2lcov test.exec ; then
    expect_log winbat 'wintools/xml2lcov.bat --format jacoco'
    expect_data winbat winbat.info '^SF:src/com/example/Widget.java$'
fi

# with no such sibling, the file itself is used, however little -x thinks of it.
#  Here that fails, because this file really is not executable - but it fails at
#  the point of running it, which is the point:  a Windows run gets this far,
#  and an LCOV installation there is nothing but files -x rejects
if run winplain 1 -o winplain.info -s src -c bin -jar $JAR --java ./fakejava \
       --xml2lcov nominal.xml test.exec ; then
    expect_log winplain "unable to execute 'nominal.xml'"
    reject_log winplain 'is not an executable file'
fi

# a sibling which -x rejects as well is no better than the script:  the script
#  is what gets run, which is what the failure names
mkdir -p winnobat
printf 'not an executable file\n' > winnobat/xml2lcov
printf 'not an executable file either\n' > winnobat/xml2lcov.bat
chmod 644 winnobat/xml2lcov winnobat/xml2lcov.bat
if run winbadbat 1 -o winbadbat.info -s src -c bin -jar $JAR \
       --java ./fakejava --xml2lcov winnobat/xml2lcov test.exec ; then
    expect_log winbadbat "unable to execute 'winnobat/xml2lcov'"
fi

# and a name which names nothing is still the usage error it always was:  the
#  hack takes a file which is there and cannot be shown to be runnable, not a
#  file which is not there
if run winnotool 1 -o winnotool.info -s src -c bin -jar $JAR \
       --java ./fakejava --xml2lcov nosuchtool test.exec ; then
    expect_log winnotool "'nosuchtool' is not an executable file"
    expect_log winnotool "use '--xml2lcov'"
fi

unset LCOV_ASSUME_WINDOWS

# ---------------------------------------------------------------------------
# 16. Windows path names, on a perl whose path syntax is Unix's
# ---------------------------------------------------------------------------

# A git-bash, MSYS or Cygwin perl has Unix path semantics and knows nothing of
#  drive letters, so 'Z:\dir\file' - which is what a Windows caller writes, in
#  an option, in an environment variable or in the name it invokes the script by
#  - names nothing that perl can open.  The drives are mounted in such an
#  installation, so the same file has a name it does understand, and jacoco2lcov
#  translates every path it is handed to that name - its own options here, and
#  the common ones in lcovutil.pm, which is where the translation itself lives.
#  'LCOV_DRIVE_MOUNT' is the test hook:  it says which directory to look for the
#  drives in, and turns the translation on, which is what lets any of this run
#  here.
# The fixtures below are a 'Z:' drive holding what a run needs - the jar, a java,
#  sources, classes, a plugin, execution data, a root directory to work in, and
#  an installation of the tools themselves
WINMOUNT=`pwd`/winmount
export LCOV_DRIVE_MOUNT=$WINMOUNT
mkdir -p $WINMOUNT/z/jacoco/lib $WINMOUNT/z/javahome/bin $WINMOUNT/z/classes \
    $WINMOUNT/z/out $WINMOUNT/z/bin
cp $JAR $WINMOUNT/z/jacoco/lib/jacococli.jar
cp fakejava $WINMOUNT/z/javahome/bin/java
printf 'not really a class file\n' > $WINMOUNT/z/classes/Widget.class
cp -r src $WINMOUNT/z/src
cp -r plugins $WINMOUNT/z/plugins
cp -r droot $WINMOUNT/z/droot
cp test.exec $WINMOUNT/z/test.exec
XML2LCOV=`readlink -f ${XML2LCOV_TOOL}`
ln -s $XML2LCOV $WINMOUNT/z/bin/xml2lcov
#  the 'winself' case below runs a copy of the script from this bin directory,
#   and a copy of the script loads its modules from '../lib' of wherever it was
#   found - so this installation needs that directory too
ln -s `readlink -f $LCOV_HOME/lib` $WINMOUNT/z/lib

# the jar and the java, written both ways a Windows path can be written:  the
#  separator is a backslash or a forward slash, and either of them arrives
if run winjar 0 -o winjar.info -s src -c bin -v \
       --jar 'Z:\jacoco\lib\jacococli.jar' --java 'Z:/javahome/bin/java' \
       test.exec ; then
    expect_java winjar "$WINMOUNT/z/javahome/bin/java -jar $WINMOUNT/z/jacoco/lib/jacococli.jar report test.exec --classfiles bin --sourcefiles src --xml TMPXML"
    expect_data winjar winjar.info '^SF:src/com/example/Widget.java$'
fi

# the source and class directories, the execution data and the output file:  the
#  translated names are what JaCoCo is told to use, because they are the names
#  which name those files here
if run windirs 0 -o 'Z:/out/windirs.info' -s 'Z:\src' -c 'Z:\classes' -v \
       --jar 'Z:\jacoco\lib\jacococli.jar' --java ./fakejava 'Z:\test.exec' ; then
    expect_java windirs "./fakejava -jar $WINMOUNT/z/jacoco/lib/jacococli.jar report $WINMOUNT/z/test.exec --classfiles $WINMOUNT/z/classes --sourcefiles $WINMOUNT/z/src --xml TMPXML"
    expect_data windirs $WINMOUNT/z/out/windirs.info "^SF:$WINMOUNT/z/src/com/example/Widget.java\$"
fi

# a plugin root is expanded after it is translated, so the directories it
#  contributes are named the way this perl can use them too - and '--xml' names
#  the report to keep in the same way
if run winplugin 0 -o winplugin.info -p 'Z:\plugins\pluginA' \
       --xml 'Z:/out/winplugin.xml' --jar 'Z:\jacoco\lib\jacococli.jar' \
       --java ./fakejava -v test.exec ; then
    expect_java winplugin "./fakejava -jar $WINMOUNT/z/jacoco/lib/jacococli.jar report test.exec --classfiles $WINMOUNT/z/plugins/pluginA/target/classes --sourcefiles $WINMOUNT/z/plugins/pluginA/src/main/java --xml $WINMOUNT/z/out/winplugin.xml"
    if [ ! -f $WINMOUNT/z/out/winplugin.xml ] ; then
        fail winplugin 'the XML report was not kept where it was asked for'
    fi
fi

# the tools to run are paths as well
if run wintool 0 -o wintool.info -s src -c bin -v \
       --xml2lcov 'Z:/bin/xml2lcov' --jar 'Z:\jacoco\lib\jacococli.jar' \
       --java ./fakejava test.exec ; then
    expect_log wintool "$WINMOUNT/z/bin/xml2lcov --format jacoco"
    expect_data wintool wintool.info '^SF:src/com/example/Widget.java$'
fi

# the separators do not have to be consistent, and a path does not have to name
#  a drive at all:  a backslash is the Windows separator wherever it appears, so
#  a relative Windows path and a UNC name - which is '//host/share/...' on these
#  perls - are usable once the separators are turned around.  'winmount\z\src' is
#  the relative one, and it names the same sources as the runs above
if run winmixed 0 -o winmixed.info -s 'winmount\z\src' -c 'Z:\classes' -v \
       --jar 'Z:\jacoco/lib\jacococli.jar' --java ./fakejava test.exec ; then
    expect_java winmixed "./fakejava -jar $WINMOUNT/z/jacoco/lib/jacococli.jar report test.exec --classfiles $WINMOUNT/z/classes --sourcefiles winmount/z/src --xml TMPXML"
    expect_data winmixed winmixed.info '^SF:winmount/z/src/com/example/Widget.java$'
fi

# and so is the root directory to work in, which everything else is relative to.
#  The stub is told where to write from here, because it runs in that directory
SAVED_STUB_LOG=$STUB_LOG
export STUB_LOG=`pwd`/fakejava.log
export STUB_REPORT=`pwd`/nominal.xml
if run windroot 0 -d 'Z:\droot' -o windroot.info -s src/main/java \
       -c target/classes -v --jar 'Z:\jacoco\lib\jacococli.jar' \
       --java $WINMOUNT/z/javahome/bin/java execdir/second.exec ; then
    expect_log windroot "working in root directory '$WINMOUNT/z/droot'"
    expect_data windroot $WINMOUNT/z/droot/windroot.info '^SF:src/main/java/com/example/Widget.java$'
fi
export STUB_LOG=$SAVED_STUB_LOG
STUB_REPORT=

# a drive this installation has not mounted has no name to be translated to, so
#  it is left as it stands and the drive the user named is what the complaint
#  names
if run winnodrive 1 -o winnodrive.info -s src -c bin \
       --jar 'Q:\jacoco\lib\jacococli.jar' --java ./fakejava test.exec ; then
    expect_log winnodrive "'Q:/jacoco/lib/jacococli.jar' is not a readable file"
fi

# a UNC name is a path on these perls too, written '//host/share/...'.  There is
#  no such share here, so what this shows is the name which was looked for
if run winunc 1 -o winunc.info -s src -c bin \
       --jar '\\build01\share\jacoco\jacococli.jar' --java ./fakejava \
       test.exec ; then
    expect_log winunc "'//build01/share/jacoco/jacococli.jar' is not a readable file"
fi

# the name the script was invoked by is translated too - which is what decides
#  where the tools it runs come from, and what the failing Windows run got
#  wrong.  This one is a copy of the script under the mounted drive, invoked by
#  the drive name:  the xml2lcov which runs is the one beside the copy.
#  Perl opens the script itself, so the name has to name something from here as
#  well - hence the link;  and coverage is off, because Devel::Cover would
#  record a second file for a second path to the same script
SAVED_JACOCO2LCOV_TOOL=$JACOCO2LCOV_TOOL
SAVED_COVER=$COVER
WINSELF='Z:\bin\jacoco2lcov'
cp `readlink -f $JACOCO2LCOV_TOOL` $WINMOUNT/z/bin/jacoco2lcov
chmod 755 $WINMOUNT/z/bin/jacoco2lcov
ln -s $WINMOUNT/z/bin/jacoco2lcov "$WINSELF"
COVER=
JACOCO2LCOV_TOOL="perl $WINSELF"
if run winself 0 -o winself.info -s src -c bin -v \
       --jar 'Z:\jacoco\lib\jacococli.jar' --java ./fakejava test.exec ; then
    expect_log winself "$WINMOUNT/z/bin/xml2lcov --format jacoco"
    expect_java winself "./fakejava -jar $WINMOUNT/z/jacoco/lib/jacococli.jar report test.exec --classfiles bin --sourcefiles src --xml TMPXML"
    expect_data winself winself.info '^SF:src/com/example/Widget.java$'
    #  and the drive name reached neither the messages nor the temporary
    #   directory the script made for itself
    reject_log winself 'Z:'
fi
JACOCO2LCOV_TOOL=$SAVED_JACOCO2LCOV_TOOL
COVER=$SAVED_COVER

unset LCOV_DRIVE_MOUNT

# ---------------------------------------------------------------------------
# 17. --version-script
# ---------------------------------------------------------------------------

# A JaCoCo report does not say which version of the source it describes, so the
#  only version there can be is the one the callback computes from the source -
#  and computing it as the translated data is read back in is what
#  'compute_file_version' asks for.  jacoco2lcov turns that on for itself when a
#  version script is named:  a flag which quietly wrote no VER: record would be
#  no use, because the report step computes a version for the source it reads
#  and stops when the data it is shown has nothing to compare against.
#  'echo' stands in for a version script - it prints the name it is handed,
#  which is enough to show whose version was computed
if run version 0 -o version.info -s src -c bin -jar $JAR --java ./fakejava \
       --version-script echo test.exec ; then
    expect_data version version.info '^VER:src/com/example/Widget.java$'
    expect_data version version.info '^VER:src/com/example/Helper.java$'
    #  and the data the version belongs to is all still there
    expect_data version version.info '^BRDA:5,0,0,1$'
    expect_data version version.info '^FNA:0,1,com.example.Widget.run()V$'
fi

# only an unset value is defaulted, so a caller who does not want the
#  computation can still say so
if run noversion 0 -o noversion.info -s src -c bin -jar $JAR \
       --java ./fakejava --version-script echo --rc compute_file_version=0 \
       test.exec ; then
    reject_data noversion noversion.info '^VER:'
fi

# and with no version script there is nothing to compute a version with, so
#  there is none in the result:  the default is not turned on for its own sake
if run noscript 0 -o noscript.info -s src -c bin -jar $JAR \
       --java ./fakejava test.exec ; then
    reject_data noscript noscript.info '^VER:'
fi

restore_permissions

if [ $STATUS == 0 ] ; then
    echo "Tests passed"
else
    echo "Tests failed"
fi
exit $STATUS
