# ============================================================================
# setup_common.sh -- shared setup for the split 'errs' msgtest tests.
#
# The original monolithic msgtest.sh was split into msgtest1.sh .. msgtest4.sh
# so its ~100 tool invocations (dominated by genhtml report runs, including the
# 14-run scriptErr loop, the 10-run expect loop and the 16-run rcErr loop) can
# run as four independent tests in parallel.  Each part runs in its own working
# directory (partN.d) so the parts cannot collide on the many fixed output
# names (initial.info, script_err.log, foo, rcErr, inconsistent, expect, ...).
#
# This file is *sourced* by each part after it has sourced ../../common.tst.
# It derives the compiler-version option variables, creates and cd's into the
# part's private working directory, symlinks in the source and support files
# referenced by relative path, compiles + runs the instrumented binary, and
# produces the two capture inputs shared across parts:
#     initial.info (+ initial_all.log)   -- consumed by every part
#     version.info (+ version.log)       -- consumed by the callback-error part
# ('build.info' is produced inline by part 1, which is the only part that uses
# it, exactly as the original script did.)
#
# It performs only capture die-guards; the behavioural assertions (e.g. the
# '--all ignored' warning check) stay in the individual parts.
#
# There is a real p4/git annotation dependency here: with IS_P4=1 the cache and
# epoch tests actually run p4annotate on the source.  'test.cpp' is therefore
# symlinked to the real p4-controlled ../simple/simple.cpp so version-script and
# annotate callbacks resolve it via p4, exactly as the original did.
#
# Callers set WORKDIR (e.g. WORKDIR=part1.d) before sourcing.
# ============================================================================

if [ -z "$WORKDIR" ] ; then
    echo "setup_common.sh: WORKDIR not set" >&2
    exit 1
fi

if ! type "${CXX}" >/dev/null 2>&1 ; then
        echo "Missing CXX tool: $CXX" >&2
        exit 2
fi

# SRCDIR = the real test directory (where the source and support files live);
# we are sitting in it because common.tst did ROOT=`pwd`.
SRCDIR=`pwd`

setup_die() {
    echo "setup_common: $1" >&2
    exit 1
}

SELECT_SCRIPT=$SCRIPT_DIR/select.pm
CRITERIA_SCRIPT=$SCRIPT_DIR/criteria.pm
GITBLAME_SCRIPT=$SCRIPT_DIR/gitblame.pm
GITVERSION_SCRIPT=$SCRIPT_DIR/gitversion.pm
P4VERSION_SCRIPT=$SCRIPT_DIR/P4version.pm
SIMPLIFY_SCRIPT=$SCRIPT_DIR/simplify.pm
HISTORY_SCRIPT=$SCRIPT_DIR/history.pm

if [ 1 == "$USE_GIT" ] ; then
    # this is git
    VERSION_SCRIPT=${SCRIPT_DIR}/gitversion.pm
    ANNOTATE_SCRIPT=${SCRIPT_DIR}/gitblame.pm
else
    VERSION_SCRIPT=${SCRIPT_DIR}/getp4version
    ANNOTATE_SCRIPT=${SCRIPT_DIR}/p4annotate.pm
fi

# filter out the compiler-generated _GLOBAL__sub_... symbol
LCOV_BASE="$EXTRA_GCOV_OPTS --branch-coverage $PARALLEL $PROFILE --no-external --ignore unused,unsupported --erase-function .*GLOBAL.*"
LCOV_OPTS="$LCOV_BASE"
DIFFCOV_OPTS="--filter line,branch,function --function-coverage --branch-coverage --demangle-cpp --prefix $PARENT_VERSION $PROFILE "

# old version of gcc has inconsistent line/function data
IFS='.' read -r -a VER <<< `${CC} -dumpversion`
if [ "${VER[0]}" -lt 5 ] ; then
    # can't get branch coverpoints in 'initial' mode, with ancient GCC
    IGNORE="--ignore usage"
elif [ "${VER[0]}" -ge 14 ] ; then
    ENABLE_MCDC=1
    BASE_OPTS="$BASE_OPTS --mcdc"
    # enable MCDC
    COVERAGE_OPTS="-fcondition-coverage"
fi

NO_INITIAL_CAPTURE=0
if [[ "${VER[0]}" -gt 4 && "${VER[0]}" -lt 7 ]] ; then
    # no data generated by initial capture
    IGNORE_EMPTY="--ignore empty"
    NO_INITIAL_CAPTURE=1
fi

if [ 1 == $NO_INITIAL_CAPTURE ] ; then
    # all test test use --initial
    echo 'all tests skipped'
    exit 0
fi

IGNORE_MSG="'--all' ignored"
if [ "${VER[0]}" -lt 5 ] ; then
    IGNORE_MSG="--initial cannot generate branch coverage data with this compiler/toolchain version"
fi

# annotation is only ignorable when this is neither a git nor a p4 checkout
if [ $IS_GIT == 0 ] && [ $IS_P4 == 0 ] ; then
    IGNORE_ANNOTATE='--ignore annotate'
fi

# --------------------------------------------------------------------------
# Create and enter the private working directory.
# --------------------------------------------------------------------------
rm -rf "$SRCDIR/$WORKDIR"
mkdir -p "$SRCDIR/$WORKDIR"
cd "$SRCDIR/$WORKDIR" || exit 1

# Support files referenced by relative path in the various parts.  Symlink them
# all so every part has a uniform environment regardless of which slice it runs.
ln -s "$SRCDIR/select.sh"         select.sh
ln -s "$SRCDIR/genError.pm"       genError.pm
ln -s "$SRCDIR/parallelFail.pm"   parallelFail.pm
ln -s "$SRCDIR/missingRestore.pm" missingRestore.pm
ln -s "$SRCDIR/MsgContext.pm"     MsgContext.pm
ln -s "$SRCDIR/mcdc_errs.dat"     mcdc_errs.dat

echo `which gcov`
echo `which lcov`

# test.cpp must resolve (via symlink) to the real p4-controlled source so the
# version-script and p4annotate callbacks can look it up in p4.
ln -s "$SRCDIR/../simple/simple.cpp" test.cpp
${CXX} --coverage test.cpp || setup_die "compile failed"
./a.out

# --------------------------------------------------------------------------
# initial.info -- consumed by every part.  Capture with tee so part 1 can
# assert on the '--all ignored' warning in initial_all.log.
# --------------------------------------------------------------------------
echo lcov $LCOV_OPTS --capture --directory .  --initial --all --output-file initial.info --test-name myTest $IGNORE
$COVER $LCOV_TOOL $LCOV_OPTS --capture --directory . --initial --all --output-file initial.info --test-name myTest $IGNORE 2>&1 | tee initial_all.log
if [ 0 != ${PIPESTATUS[0]} ] ; then
    setup_die "lcov --capture (initial) failed"
fi

# --------------------------------------------------------------------------
# version.info -- consumed by the callback-error part (version-script tests).
# --------------------------------------------------------------------------
echo lcov $LCOV_OPTS --capture --directory .  --output-file version.info --test-name myTest --version-script $SCRIPT_DIR/getp4version
$COVER $LCOV_TOOL $LCOV_OPTS --capture --directory .  --output-file version.info --test-name myTest --version-script $SCRIPT_DIR/getp4version | tee version.log
if [ 0 != $? ] ; then
    setup_die "lcov --capture (version) failed"
fi
