include ../../common.mak

# deleted some old tests because generated data is inconsistent
# Those tests have probably outlived their usefulness.
TESTS := prune.sh track.sh aggdir.sh

clean:
	rm -f *.info *.log *.c prune prune2 prune3 track prune3s prune3t
	rm -rf spacedir patdir "q'dir"
