include ../../common.mak

# deleted some old tests because generated data is inconsistent
# Those tests have probably outlived their usefulness.
TESTS := prune.sh track.sh

clean:
	rm -f *.info prune prune2 prune3 track prune3s prune3t
